### PR TITLE
Companion global variables refactor

### LINKED ISSUE #4947: Companion 2.2.0 inability to edit new global variable parameters
Can be edited on radio and Companion Simulator but cannot find in Companion model edit.

Ubuntu 16.04 Taranis X9D+

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #4947
Add radio gvar refactoring to Companion
Tested on X9D+ radio file

Note Companion Simulator radio outputs still broken as gvars displayed without using precision.

### CODE REVIEW

**Review by bsongis — COMMENTED** [review]
Seems all good

**Comment by bsongis** [comment]
> Note Companion Simulator radio outputs still broken as gvars displayed without using precision

Do you need help for this? Is it something which is not saved into the EEPROM?

**Comment by bsongis** [comment]
I merge this PR now, it will be in next release

**Comment by elecpower** [comment]
@bsongis the values are correct in the simulated radio gui. The bug is the separate Radio Outputs window. I've had a quick look and does not seem (to me) to an easy fix due to the coding design but I will spend some more time on it this week and let you know if I need some help or it is beyond my ability (have been using this project to teach myself C++}

**Comment by kilrah** [comment]
It's issue #4529

**Pull request merged**
