### PR TITLE
Changes to allow LUA to access DSM Forward Programming

### PR DESCRIPTION
**Pull request by pascallanger**
The code change proposed is the background fundation to get LUA to access the needed information to enable Forward Programming.
The LUA script is not included since it is WIP. It will be added later on when a stable version will be available.

### CODE REVIEW

**Comment by dsmithwc04** [comment]
Hello! I'm not familiar with this process but did this lua script end up getting released yet for the Radiomaster tx16s?

**Comment by pascallanger** [comment]
It's available in the OpenTX nightly builds.

**Comment by dsmithwc04** [comment]
I'm sorry but how do I download the nightly build?  Open TX 2.3.3 is the latest nightly build correct?  I'm new to this and I appreciate your time!
Sincerely, Dan Smith. 

    On Wednesday, September 30, 2020, 05:03:33 PM EDT, pascallanger <notifications@github.com> wrote:  
 
 


It's available in the OpenTX nightly builds.

**Comment by dsmithwc04** [comment]
I downloaded companion 2.3.10N334 and ran it.  I don't see the firmware to write to the tx though?  
Sincerely, Dan Smith. 

    On Wednesday, September 30, 2020, 05:29:07 PM EDT, Daniel Smith <dsmithwc04@yahoo.com> wrote:  
 
 I'm sorry but how do I download the nightly build?  Open TX 2.3.3 is the latest nightly build correct?  I'm new to this and I appreciate your time!
Sincerely, Dan Smith. 

    On Wednesday, September 30, 2020, 05:03:33 PM EDT, pascallanger <notifications@github.com> wrote:  
 
 


It's available in the OpenTX nightly builds.

**Pull request merged**
