### PR TITLE
Simple cleanup of #if defined

### PR DESCRIPTION
**Pull request by floaledm**

### CODE REVIEW

**Comment by schwabe** [comment]
That commit looks like it adds longer strings to AVR. Have you checke that this does not increase the size of the AVR binaries? (make firmware-size)

**Comment by floaledm** [comment]
How do I check that?

**Comment by projectkk2glider** [comment]
I think it is good, @floaledm just removed the fidefs that could not be reached - ie dead code.

**Comment by floaledm** [comment]
You got it Damjan. Looked like there was some dead code. That's it...

**Comment by kilrah** [comment]
Yup, copypasta relics...

**Pull request merged**
