### PR TITLE
X7 : fix calibration interuption

### LINKED ISSUE #4833: X7 calibration interuption issue 2.2N369
2.2N369
X7 calibration - long menu long page - calibration menu. 
press enter to start - pressed
press enter when stick and pots in center - pressed
now not continue press exit it skip to home screen 
process is canceled
from this time is not posible to use page to browse the main setting radio menu or model menu. page button not do any action. 

Radio must be restarted to make it work again.

### PR DESCRIPTION
**Pull request by 3djc**
It does seem to do the job, but not overly happy with the fix

This fixes #4833

### CODE REVIEW

**Comment by bsongis** [comment]
Do we have the same problem on X9D? on X12S?

**Comment by 3djc** [comment]
Nop

**Comment by bsongis** [comment]
Do we have the same hack for those other boards?

**Comment by 3djc** [comment]
No, it's much cleaner on those other boards, but there is already something 'odd', since menuCalibrationState is mentionned only once in x9/x12 navigation routine, and already 3 in x7 before this fix.

So do I like this fix : no, but I was not able to come with a better one, but I'm sue I know someone who can ;)

**Comment by bsongis** [comment]
Excellent, it looks like others boards code now!

**Pull request merged**
