### PR TITLE
Companion enhancements - checklist editor, print and compare

### LINKED ISSUE #5334: Limit checklist editor to available caracters
I'm a french OpenTx user and accentuated caracters are common.
I don't need to display them on the radio but i regularly forget that they won't display well on it.

Maybe the checklist editor caracters could be limited to a caracter "whitelist" ?

image

image

### PR DESCRIPTION
**Pull request by elecpower**
Print and compare (includes PR #6349)
- Add global functions if enabled for model
- Add checklist contents if display enabled

Checklist
- Remove accents fixes #5334
- Display cursor position coords
- Force fixed width font
- Refactor to use helpers

Sorry, shared helper functions and cherry picking commits not clean so combined. Will close PR 6349.

### CODE REVIEW

**Comment by mpaperno** [comment]
Hi Neil, there's an improved version of `removeAccents()`  (more efficient and handles upper case) in the 2.3 branch, merged from here: https://github.com/opentx/opentx/pull/6180/files#diff-97d607df8349d6b8c72b3d2c558787e2

**Comment by elecpower** [comment]
@mpaperno thanks. @bsongis @3djc @kilrah @mpaperno should I be targeting the 2.3 branch for my enhancement PRs from now on?

**Comment by 3djc** [comment]
@elecpower yes please, do target 2.3 branch. For now, do expect some delay before your PR get merged in 2.3. It is not at all because your PR are not valued, quite the contrary, it is because we are trying internaly a lot of things, and merging that work will already be chalenging enough. Fortunalty, Companion has not been changed much yet, so mergeing your changes after we do the 'big merge' should not be too painfull. Once again, thanks a lot for your work, and do not hesitate to stop by our rocket.chat should you feel like it

**Comment by bsongis** [comment]
Right, it will be 2.3
I expect we will be ready in less than 15 days, but I cannot promise

**Comment by elecpower** [comment]
Okay I'll hold off any more PRs until the new 2.3 is released. When you get around to the PR backlog just add comments to the ones you would like me to rebase to 2.3 and retest.

**Comment by 3djc** [comment]
No no, he meant we should merge our internal tests into 2.3 branch in a couple of weeks, enabling working toward future 2.3,  At that point, the PR backlog, will be treated, and during that work, you'll be able to submit more PR for fast treatment so they are included in 2.3

**Comment by bsongis** [comment]
@elecpower would you port this PR to the 2.3 ? It would be the right timing, or do you prefer we do it for you?

**Comment by elecpower** [comment]
@bsongis I am happy to port if you can wait a day.

**Comment by 3djc** [comment]
Sure, take your time, we are still working on 2.3

**Comment by bsongis** [comment]
@elecpower thanks a lot, and yes it can wait one day without issue, I am just willing to reduce the PR list during this week

**Comment by bsongis** [comment]
Done in 2.3

**Pull request closed without merging**
