### PR TITLE
Companion gvar refactor for special functions to match radio

### LINKED ISSUE #5311: Min/Max settings of GVs seem to have no effect
Companion 2.2.0 simulator, Taranis X9D

1. In the pop up menu of GV1 settings, I set MAX to 50.
2. I set a special function: adjust GV1 with S1 as source.
3. When I move S1 from -100 to 100, GV1 moves accordingly from -100 to 100. Shouldn’t it be clipped to 50 or even scaled to 50 in the positive part?

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #5311

### CODE REVIEW

**Comment by 3djc** [comment]
Not sure it's fully working:

image

**Comment by elecpower** [comment]
@3djc what you have shown I reported in #5360. This PR is another piece of the refactoring.

**Comment by 3djc** [comment]
Sorry, was confused by the timing and gvar mention, my applogies :)

**Comment by elecpower** [comment]
@3djc no problem. I reported the sim bug as it may take a while to fix.

**Pull request merged**
