### PR TITLE
Updated French Translation

### PR DESCRIPTION
**Pull request by LapinFou**
Latest Fr translation.

Could you, please, check the `Warn(%1)` translation? I don't know what is the context. So, I'm not sure of the translation.

### CODE REVIEW

**Comment by kilrah** [comment]
You can set a warning beep on a mixer line.

**Comment by LapinFou** [comment]
Thanks for the context. 😊👍
So, I translated `Warn` with `Alerte`.

**Comment by 3djc** [comment]
https://www.youtube.com/watch?v=luYF1H642FE !

**Comment by LapinFou** [comment]
> 
> 
> https://www.youtube.com/watch?v=luYF1H642FE !

😁😁😂🤣

**Comment by LapinFou** [comment]
Du coup, je pense que la traduction est la bonne dans ce contexte.
Sauf si vous souhaitez que je fasse une modif, vous pouvez faire un *merge* de ce PR.

@+
Seb

**Pull request merged**
