### PR TITLE
Forward key events to fullscreen LUA widgets

### LINKED ISSUE #3821: Horus X12S N357 - LUA widget - key event
Is there no key event on widget lua scripting on horus?

Or do i miss something? How do you work with keys in a widget?

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
closes #3821

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@lshems in case you'd like to test: now is the time :-)

**Comment by raphaelcoeffic** [comment]
Here is what I used to test:
```lua
local function createWidget()
end

local function refreshWidget(widget, ev)
   local ev_txt = ""
   if ev == EVT_VIRTUAL_EXIT then
      ev_txt = "EXIT"
   elseif ev == EVT_VIRTUAL_ENTER then
      ev_txt = "ENTER"
   elseif ev == EVT_TELEM_BREAK then
      ev_txt = "TELEM BREAK"
   elseif ev == EVT_SYS_BREAK then
      ev_txt = "SYS BREAK"
   elseif ev == EVT_MODEL_BREAK then
      ev_txt = "MODEL BREAK"
   elseif ev == EVT_VIRTUAL_NEXT then
      ev_txt = "NEXT"
   elseif ev == EVT_VIRTUAL_PREVIOUS then
      ev_txt = "PREVIOUS"
   end
      
   lcd.drawText(100, 100, ev_txt, DBLSIZE);
end

return { name="TestEv", options={}, refresh=refreshWidget, create=createWidget }
```

**Comment by lshems** [comment]
Nice. This night nightlies?

Still having a hard time compiling myself

**Comment by raphaelcoeffic** [comment]
> Nice. This night nightlies?
> 
> Still having a hard time compiling myself

nope, at least not as long as it's not merged.

**Comment by lshems** [comment]
Ok, so full screen only.

Could this be changed to first widget in main screen only?

Would add a lot more flexibility without adding complexity.

**Comment by raphaelcoeffic** [comment]
Possibly, this here was the broad consensus, as far as I remember. It will probably be improved further in 2.4 to support focusing on a specific widget, which would then have the controls (thus losing the keys used to control focus change).

**Comment by raphaelcoeffic** [comment]
@jfrickmann Would this work for your app?

**Comment by jfrickmann** [comment]
> @jfrickmann Would this work for your app?

I think so. Thanks!

**Comment by teckel12** [comment]
This would be a very powerful addition to full-screen widgets on the Horus!  Limiting it to full-screen widgets only removes any possible conflicts.  Can't think of a good reason why this OpenTX enhancement would cause any issues.

Nice work @raphaelcoeffic !

**Comment by lshems** [comment]
Whats happening? No updates apparently?

**Comment by kilrah** [comment]
Complete UI redesign in progress for 2.4.

**Comment by lshems** [comment]
What's up?

**Pull request closed without merging**
