### PR TITLE
3djc/faster local commit tests

### PR DESCRIPTION
**Pull request by 3djc**
Allow passing desired core usage for commit-tests (speed up local execution)
Usage:
commit-tests.sh -j=8
or
commit-tests.sh --jobs=8

Passing no arguments defaults to two cores used

On an i7@3.7Ghz : 2 cores : 13m14secs
with 8 cores : 8m11secs

### CODE REVIEW

**Comment by schwabe** [comment]
Looks good. Two nitpickings

I would prefer -j8 instead of -c8.
${foo} is nicer in scripts than $foo

**Comment by 3djc** [comment]
If you can find me a long (--) version starting with 'j' and making sense, you got it

**Comment by schwabe** [comment]
--jobs? :)

**Comment by 3djc** [comment]
Yeah, never liked it in make hence my resistance, but you know what they say, resistance is futile !

**Pull request merged**
