### PR TITLE
Disable interrupts before jump to application in horus bootloader

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
As far as I could see, it seems SysTicks interrupt is not enabled at this point. Did I forget anything else?

### CODE REVIEW

**Comment by bsongis** [comment]
Today we have those variables, we need to think if they are all 3 needed:
- `shutdownRequest`
- `shutdownReason`
- `powerupReason` (NOINIT)

**Comment by bsongis** [comment]
Cases to take care / test:
1) Normal start
2) Exit from bootloader
3) Soft reset (from the application)
4) Watchdog reset

**Comment by raphaelcoeffic** [comment]
> Soft reset (from the application)

Do we have such? What happens then?

And what about `NVIC->ICER`? Should I take care of that?

**Comment by bsongis** [comment]
We have a soft reset when "Reset from factory"

**Comment by MikeBland** [comment]
Soft Reset from the application.
When using the erskyTx bootloader, I have an option to run an "app". To exit such an app (and the bootloader really), it is best to use the NVIC_SystemReset() function as this guarantees the main openTx application is started with a completely clean slate, no interrupts or DMA left possibly enabled and active. and all I/O registers reset to default values, so exactly the same as a power on.
Since there is a dedicated flag in the RCC_CSR register that is set when this occurs, I cannot see why openTx cannot just test for this flag being set to determine a controlled restart has been requested. I believe only this flag is set in the CSR. Flags in the CSR should, of course, all be cleared after they have been read by the main application.
If required, a special value could be written to one of the RTC backup registers to confirm the soft reset is valid, with the RTC backup register being cleared immediately after being read. Different values could be used to indicate different reasons for the soft reset if necessary.

**Comment by bsongis** [comment]
Mike we are working on another approach, taking into account your concern.

**Comment by bsongis** [comment]
In fact it's even exactly what you are proposing: "Different values could be used to indicate different reasons for the soft reset if necessary."

**Comment by bsongis** [comment]
Replaced by #7096

**Pull request closed without merging**
