### PR TITLE
[Horus] Internal module antenna selection support

### PR DESCRIPTION
**Pull request by kilrah**
Don't merge yet, for discussion...

We should probably have a confirmation popup when going from internal to external for the user to make sure there is an antenna installed on the external port before actually switching.

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Do you know if IXJT has any internal `antenna missing` protection? Or does selecting external antenna while no antenna connected result in burned transmitter?

**Comment by kilrah** [comment]
No idea. I intend to do some tests and measurements (I have RF test equipment) once I get my radio. I would be surprised if there is an auto shutdown.

**Comment by bsongis** [comment]
Yes a confirmation would be nice!

**Comment by kilrah** [comment]
Done, might still want to wait for tests to merge...

**Comment by kilrah** [comment]
Tested and working. There is NO protection, selecting external antenna with none attached results in SWR about 80-90. 
By the way, the SWR warning is not functional.

**Pull request merged**
