### PR TITLE
x7 rssi indicator

### PR DESCRIPTION
**Pull request by 3djc**
image

### CODE REVIEW

**Comment by bsongis** [comment]
No issue with the timer mode?

**Comment by 3djc** [comment]
image

**Comment by bsongis** [comment]
Then the flight mode name?

**Comment by 3djc** [comment]
Hum there is already an issue with flight mode, which accept 6 chars when only 5 ish can be displayed beofre it hits timer. I can probably push the Batt a couple of pixel left, timer right, leaving enough space for flight mode, and enough space for an horizontal version  bellow flight mode

image

**Comment by 3djc** [comment]
New version:

image

**Comment by kilrah** [comment]
Maybe mode name 1 pixel further left?

**Comment by 3djc** [comment]
image

**Pull request merged**
