### PR TITLE
Add RX numbers to CPN models list

### PR DESCRIPTION
**Pull request by elecpower**
Enhancement #5088
Lists RX # even if not displayed/editable in model edit. This allows residual configuration to be visible which may be the cause of issues. Residual configuration possible from changing RX type and copying models.

\+ means # referenced by more than one model
\* means # references non-existent model

screenshot from 2019-01-11 21-19-20

screenshot from 2019-01-11 21-19-52

### CODE REVIEW

**Comment by kilrah** [comment]
Nice... what do you mean by

> * means # references non-existent model

**Comment by elecpower** [comment]
@kilrah eg X9D+ Index 04 has RX# 06 but that slot is empty so no bound receiver

**Comment by kilrah** [comment]
That's kind of irrelevant, and doesn't say anything about whether a receiver is bound or not

**Comment by notlebowski** [comment]
I welcome this feature a lot, but can't you use red for a double reference and leave it at that?
Thanks for making this

**Comment by elecpower** [comment]
@kilrah agree pointing to a valid model does not confirm an RX is bound to it. Pointing to an empty model is worth highlighting IMHO as for non-categorised radios you may have to scroll to to find the linked model. Also for some users certain digits can look the same at first glance. 
@notlebowski see next commit for red.

**Comment by elecpower** [comment]
screenshot from 2019-01-13 08-31-22

**Comment by bsongis** [comment]
Do we really want this one in 2.2? It's in 2.3, no?

**Comment by elecpower** [comment]
If 2.2 is now bug fix only then I have not problem with closing this PR

**Comment by bsongis** [comment]
Yes, thanks!

**Pull request closed without merging**
