### PR TITLE
Schwabe/inofficial multi module21

### PR DESCRIPTION
**Pull request by kkriegel**

### CODE REVIEW

**Comment by kilrah** [comment]
?

**Comment by bsongis** [comment]
Wow 'master' is our stable branch, it's really dangerous to merge this feature there!

**Comment by schwabe** [comment]
This has already been discussed. Multi support is not going to be in a official 2.1 release. Just go with 2.2 which includes the feature. The later commits here are also backports of 2.2 that just work but somtimes take shortcuts that would not be allowed in the official repo (e.g. only English translation works).

**Comment by kkriegel** [comment]
Hi,Sorry folks, I definitely clicked something by accident on github, or maybe issued a wrong incantation in a bash prompt. Can you please tell me what it looked like from your end? I have just started on a very long learning curve to understand what the opentx code is doing under the hood, so that I can ask intelligent questions regarding my specific area of interest (revolving around DSM/DSMX, but also the multi module). Under no circumstances would I actually attempt to commit anything, or even knowingly make a stupid request. I am an electronics hardware QA and compliance engineer during the day and I use a variety of issue trackers in the pursuit of that activity. I've never had this happen before. 
I am interested in contributing in whatever way that I can. That includes testing hardware and regressing software, including serial decoding. I currently own a Taranis X9D Plus and I use it all day every weekend.
Again, my apologies.
Ken K.Cotati, CA, US 

    On Sunday, November 20, 2016 2:07 AM, Andre Bernet <notifications@github.com> wrote:
 

 ?—

**Comment by schwabe** [comment]
Feel free to come over to our chat for your questions.

**Pull request closed without merging**
