### PR TITLE
Run some task more frequently

### PR DESCRIPTION
**Pull request by 3djc**
This fixes some issue arising when synced mixer is running at "low" frequency

### CODE REVIEW

**Review by raphaelcoeffic — COMMENTED** [review]
That’s ok for me, thx!

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
It seems we have an issue with this PR. People are reporting sync going haywire sending only every 30ms, where as the module is requesting something different.

**Comment by 3djc** [comment]
Just tested on TX16S, CRSF module gives me CRSFShot indication, and Ghost tells me locked ; so I think we are sending pulses ok. Any more info available ?

**Comment by raphaelcoeffic** [comment]
https://www.facebook.com/groups/636441730280366/permalink/762563291001542/

**Comment by 3djc** [comment]
I have no elrs, so cannot test

**Comment by raphaelcoeffic** [comment]
Ok, I'll come up with a proper fix very soon.

**Comment by raphaelcoeffic** [comment]
Issue is confirmed on TBS tracer. It takes a little while to happen though.

**Comment by raphaelcoeffic** [comment]
@3djc here is the fix: https://github.com/EdgeTX/edgetx/pull/4

**Comment by JBKingdon** [comment]
Hi, has https://github.com/EdgeTX/edgetx/pull/4 been ported to OpenTX?

**Comment by raphaelcoeffic** [comment]
> Hi, has [EdgeTX/edgetx#4](https://github.com/EdgeTX/edgetx/pull/4) been ported to OpenTX?

Yes, I believe so.

**Pull request merged**
