### PR TITLE
IT language and TTS update for OpenTX V2.3.x

### PR DESCRIPTION
**Pull request by robustini**
Various additions and fix, IT should be complete, i'm sorry for yet another editing...

### CODE REVIEW

**Comment by robustini** [comment]
@bsongis can you put your eyes here?
Fails checks on ARM9X, dunno why...

**Comment by 3djc** [comment]
> @bsongis can you put your eyes here?
> Fails checks on ARM9X, dunno why...

Travis glitch, relaunched the process

**Comment by robustini** [comment]
Wait for any merge, I'm doing checks in each section.

**Comment by robustini** [comment]
Thanks @kilrah, I'm arguing with the spaces in the SYS/HARDWARE menu, already corrupted in 2.3.1, when I finish all the check I write it.

**Comment by robustini** [comment]
Everything now seems OK, but I can't check on X9D since I don't own it.
A verification with tx without the color graphic display would be welcome.
@bsongis it is better to delete my changes to the 2.3 branch yesterday because the HARDWARE section was corrupt.

**Comment by 3djc** [comment]
You can check with either simu or libsimulator ;)

**Comment by robustini** [comment]
> 
> 
> You can check with either simu or libsimulator ;)

True, now I do it.

**Comment by robustini** [comment]
Also verified on X9D and X7, the latter unfortunately having such a small display does not allow too long writings, there's some overlap of some character, but before it was the same or worse.
To adapt it perfectly to this display too, the various wordings would be reduced too, unfortunately the Italian in many terms is much longer than English.
It would be useful to have two sets of separate languages, or create other conditions within the existing one to overcome this limit.
For the rest I can't find any issues, fingers crossed...

**Comment by robustini** [comment]
From that I understand these conditions exist already in the DEFINE, correct me if I'm wrong, I don't know if they are applicable everywhere.
Example:

// For all the tx (unified)
#define TR_BATTERYWARNING      INDENT"Avviso batteria"

// For low and full graphics (separate)
#define TR_BATTERYWARNING      TR(INDENT "Avv. Batt.", INDENT "Avviso Batteria")

Is correct and applicable everywhere?
If the syntax is correct I've to update some phrases for the small displays, like the one above.

**Comment by kilrah** [comment]
Yes that's correct.

**Comment by robustini** [comment]
Ok, now it should be okay...

**Comment by robustini** [comment]
I find nothing else anomalous, everything is translated.
I will work on it further after the release candidate of 2.3.2 and users feedback.

**Comment by robustini** [comment]
I close it and open another one with global changes.

**Pull request closed without merging**
