### PR TITLE
Add support for LCD ERC12864FSF

### PR DESCRIPTION
**Pull request by universam1**
common replacement LCD needs different init data

### CODE REVIEW

**Comment by universam1** [comment]
Question to the manufacturer:
1. Would you be able to have this display available for a longer time period?
2. Please name any other display from you that has the same 30Pin connector and uses the same "different" type of init commands so we can support any of these.

"Here is our answer about the below questions;

1.This module ERC12864FSF-2 is the one of our popular product,It will be keep on sale at recent years,We will inform the customer in advance if we plan to upgrade this module,So please don't worry about it.

2.Our ERC12864FSF-4 could reach your requirement,It has same 30Pin connector and same programd as our ERC12864FSF-2,only difference is the voltage,Please refer to the datasheet for more details at http://www.ebay.com/itm/12864-128x64-GLCD-Graphic-LCD-Module-Display-SPI-Serial-ST7565P-3V-Black-White-/291022273441?pt=LH_DefaultDomain_0&hash=item43c2477ba1
"

**Comment by universam1** [comment]
this commit resolves #2188

**Comment by bsongis** [comment]
No option in the Makefile?

**Comment by universam1** [comment]
Would you mind for help out on the makefile since I'm not confident with that

**Pull request merged**
