### PR TITLE
#4179 cn translation done

### PR DESCRIPTION
**Pull request by Kongse**
translation finished

### CODE REVIEW

**Comment by bsongis** [comment]
Thanks!

**Comment by Kongse** [comment]
LOL :)

**Comment by projectkk2glider** [comment]
I checked some of the translation with Google Translate, it appears good. @Kongse thanks for this. But remember to revisit this periodically and update any changed/added strings in the future.

**Comment by kilrah** [comment]
A few things:

- I see that in the file there is often some text that comes up in "translator comments". Understand this will never be seen by users, this is only for translators to make notes to refer to later and will only appear inside of QT Linguist.

- It builds, but if I select Chinese in the menus I get English language. I guess that's becasue my system has no idea about Chinese characters. @Kongse , can you test this build?
http://www.andrebernet.ch/divers/opentx/companion-windows-2.2.0-cntest.exe

**Comment by Kongse** [comment]
@projectkk2glider Ok i would :)

@kilrah 

- Yes the comments is intended for examining and quick searching.

- Yes I've tested the build but got the same problem. When translating I renamed the translation file to italian ts file to do the job. I've thought it is intended, and will be corrected after the translation file commit, but now it seems because some code is missing.  I'm not familiar with coding so can not figure out where is the problem.

**Comment by kilrah** [comment]
Nothing seems to be missing, and I can also get it to work when swapping files... really don't understand. Will merge and we'll try to find out later

**Comment by bsongis** [comment]
swapping which files?

**Comment by kilrah** [comment]
Forget it, fixed... thought the 2nd code was the significant one, but it's the first

**Comment by Kongse** [comment]
@kilrah thank you :)

**Pull request merged**
