### PR TITLE
Fixes #2579: Added support for Trainer signal alarm

### LINKED ISSUE #2579: Checking trainer input validity
Gentlemen,

As of now, I've seen that the validity of the trainer input signal is tested properly in the code (ppmInValid is set in such case), and the trainer mode is deactivated properly, thus returning the control to the instructor. However, the issue tracking this feature (#36) was referring to the possibility to trigger some sound in such a case.

The only thing I've seen so far to implement this feature was to define a couple of logical switches checking for TR1 to TR2 being 0. Apart from the fact that this event is not really singular (could happen by accident, just leave the sticks in the middle ;-)), it is probably not really reliable.

So now my question: is there any way to directly check in a valid trainer input is available or not? I have no idea what the best way to implement that would be, btw. what the correct and logical way would be. Maybe a logical switch condition? I could implement it myself if you guys just point me into the right direction.

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
- added alarm “Trainer signal lost” & “Trainer signal recovered”.
- moved PPM capture code to trainer_input.{h,cpp}

This is the second try (see earlier push request #2593).
(Fixes #2579)

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Good, now you can see that the build of yor branch failed. Follow  details link and look at console output to find the reason.

**Comment by raphaelcoeffic** [comment]
quite nice indeed!

**Comment by projectkk2glider** [comment]
Jep, Jenkins is there to help us.

**Comment by raphaelcoeffic** [comment]
By the way, I tested the trainer input on heartbeat port (CPPM), but not on the other interfaces, and only on the X9D+. I just don't have any trainer jack here...

**Comment by raphaelcoeffic** [comment]
Any chance we can still get this one into 2.1.1?

**Comment by bsongis** [comment]
Excellent work, thanks!

**Pull request merged**
