### PR TITLE
Updated Fr Translation

### PR DESCRIPTION
**Pull request by LapinFou**

### CODE REVIEW

**Comment by bsongis** [comment]
May I ask for another translation? The Lua wizard on Horus... Complaint from a pilot on Schweizel (Vosges)

**Comment by bsongis** [comment]
Who knows you :)

**Comment by LapinFou** [comment]
I already done the translations off all LUA script. But, I never posted my translation, since I don't know how to not overwrite the English folder.... There is no multi language mechanism for the SD card.

**Comment by kilrah** [comment]
Would need to be supplied as a separate download...

**Comment by LapinFou** [comment]
OK. How should I processed then?

**Pull request merged**
