### PR TITLE
Fixes #2549 - Use PrefixPath to find the simulator libs

### LINKED ISSUE #2549: Companion Mac version
Hi,
I work on Macintosh, 
please, can you tell me when the Mac companion 2.1.x version will be available ?
thanks a lot
Jean

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Closes #2549 (*added by @projectkk2glider*)

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Looks good. 

Did you make a package, installed it and tested? Did the simulator work?

**Comment by raphaelcoeffic** [comment]
I used 'make makedmg', then mounted the .dmg and started the app. The simulator works then just like normal. The only thing is that it seems to be missing an SD card image, but I guess this is not related to OS X.

**Comment by projectkk2glider** [comment]
>The only thing is that it seems to be missing an SD card image

What do you mean? You set the SD card path in settings to a local directory that has a copy of SD card contents.

**Comment by raphaelcoeffic** [comment]
Ah ok! That was the step I missed: sorry man, I'm quite new to this whole thing here!

**Comment by projectkk2glider** [comment]
I am really glad we have someone (you) with a MAC system joining the project. It should make life much easier for all our MAC users.

**Comment by raphaelcoeffic** [comment]
Hold on, there still seems to be an issue here...

**Comment by raphaelcoeffic** [comment]
Ok, it works again: it MUST be clean build!

basically:
make clean
make makedmg

then:
open companion.dmg
double-click on the icon
open or create some models
launch simulator
be happy ;-)

**Comment by raphaelcoeffic** [comment]
is there a machine on Jenkins to build the OS X binaries? or how have you produced the packages I was downloading from open-tx.org?

**Comment by projectkk2glider** [comment]
The packages were produced manualy by (I think) @andyjenkinson. I know that @bsongis is planing to make a MAC virtual machine for the automated builds.

**Comment by bsongis** [comment]
For the moment @andyjenkinson produced the packages. I am working on a VM that will automatically build them, but it's not completely ready for 2.1.1. The packages I make are not 32bits compatible.

**Comment by raphaelcoeffic** [comment]
Hmm... Those 32bit macs are quite old, and "brew" does not support universal binaries very well. I don't think I could produce those universal binary packages in the next days.

**Pull request merged**
