### PR TITLE
Projectkk2glider/issue 4449 drawline

### LINKED ISSUE #4449: lcd.drawLine(...) gives wrong result
For the 212x64 resolution, that was corrected: https://github.com/opentx/opentx/issues/2034

But it's not for the 128x64 and 480x272 resolutions.

### PR DESCRIPTION
**Pull request by projectkk2glider**
Closes #4449

### CODE REVIEW

**Comment by bsongis** [comment]
👍

**Comment by floaledm** [comment]
Thanks for doing this! There's still an issue on X7 with drawLine(x1,y1,x2,y2,...) when x1>x2, e.g.:
untitled
is the output of this code:
`lcd.drawLine(10,10,10,20, SOLID, 0)`
`lcd.drawLine(10,10,20,10, SOLID, 0)`
`lcd.drawLine(30,40,30,30, SOLID, 0)`
`lcd.drawLine(40,30,30,30, SOLID, 0)` -> this is the line that fails to draw properly

**Comment by projectkk2glider** [comment]
@floaledm Please open a new issue with your example, this can't be reopened.

**Comment by floaledm** [comment]
Sounds good. Thanks.

**Pull request merged**
