### PR TITLE
Schwabe/cpack osx

### PR DESCRIPTION
**Pull request by schwabe**
Overhaul the packing of OpenTX on OS X. It is not perfect but it works on my development machine and is working at all (the 2.1 stuff breaks in horrible ways on my machine).

Some of the changes could also benefit other platforms but I did test/port them.

### CODE REVIEW

**Comment by bsongis** [comment]
@kilrah I let you test and merge, ok?

**Comment by kilrah** [comment]
Yep, can't build here but the result looks fine to me! Maybe just rename the app to "OpenTX Companion 2.2" instead of just companion to avoid replacing older versions

**Comment by schwabe** [comment]
@kilrah what errors are you getting? And what QT version are you using to build.

**Comment by bsongis** [comment]
@kilrah would you merge this one?

**Comment by kilrah** [comment]
Was just waiting for the rename. 
@schwabe I don't have a build setup at all on my mac at this point

**Comment by schwabe** [comment]
@kilrah I have to figure how to the rename. Just renaming the target does not work since " " and . are not allowed. Have to figure how to rename in cmake right.

**Comment by kilrah** [comment]
Hmm well if it's complicated at least have it called "companion22" like on linux... it's just so that users don't overwrite any existing 2.1 version they might have.

**Comment by schwabe** [comment]
I looked into compiling for older OS X versions. This can be theorectically done by setting ``-D CMAKE_OSX_DEPLOYMENT_TARGET="10.8"``. However, this also adds the os x version flags to the firmware compilation. 

Inquering in the #cmake irc gave me reason: Cmake does not support diferent toolchains in the same source tree build and therefore that setup is broken. The /right/ way is to have two different cmake project and add the second one via "ExternalProject_Add".

For compiling for older OS X version we need to compile only OS X targets in a seperate step.

**Comment by bsongis** [comment]
I trust you :)

**Pull request merged**
