### PR TITLE
IT TTS update

### PR DESCRIPTION
**Pull request by robustini**
I ask for revision, thanks.

### CODE REVIEW

**Comment by bsongis** [comment]
only @romoloman can check it :)

**Comment by robustini** [comment]
I hope he can watch us, it seems to me that he respected the structure of the tts for 2.3.x, but a further verification would be welcome.

**Comment by 3djc** [comment]
I'm  going to trigger a new sdcard version ofr nightlies, so you can test all that tomorow

**Comment by robustini** [comment]
> 
> 
> I'm going to trigger a new sdcard version ofr nightlies, so you can test all that tomorow

Well, I'll do more checks tomorrow.

**Pull request merged**
