### PR TITLE
Swedish translation now up-to-date and in sync with EN #3113

### PR DESCRIPTION
**Pull request by HakanBastedt**
se.h.txt updated and in sync with en.h.txt

### CODE REVIEW

**Comment by kilrah** [comment]
Looks like your file editor mangled the line endings or character encoding, the file is considered as being changed entirely...

**Comment by HakanBastedt** [comment]
Yes i noticed that but kind of ignored it I guess.
Is there any point at this time to change the line ending back to Windows style?

**Comment by kilrah** [comment]
Well we certainly don't want to mix changing line ending with actual code changes.

There is issue https://github.com/opentx/opentx/issues/2106 open to unify line endings everywhere, so until we decide to take care of it they should stay as they are. Unfortunately we've always had too many branches being worked on to really go ahead yet.

**Comment by HakanBastedt** [comment]
I don't know exactly how everything with git/github works, but if you ignore this pull request,
I can make another pull request with the correct line break.

**Comment by projectkk2glider** [comment]
Closes #3113

**Pull request merged**
