### PR TITLE
Lua task preempts long running scripts instead of killing them

### PR DESCRIPTION
**Pull request by jfrickmann**
The Lua task has been modified so scripts are preempted every 50ms instead of being killed. This is accomplished by running Lua as a coroutine with lua_resume() instead of lua_pcall, and by modifying the program flow such that Lua is called in reentrant loops.
To simplify things, I have made standalone scripts load to lsScripts like permanent scripts with reference type SCRIPT_STANDALONE, and I have removed RUN_*_SCRIPT, since we really only distinguish between fore- and background scripts. Since scripts may preempt, we cannot use "script run status" to tell if we are running telemetry or standalone (only place where it mattered). 
I have also introduced "refreshNeeded" in guiMain for non-color LCD to avoid the screen blinking if scripts are preempted.
I have flight tested it on my X9D+ and a Radiomaster TX12 flying DLGs with my SoarOTX programs and scripts for about 3 hrs total time. I have also tested that standalone and tool scripts work, and I have simulator tested X12. I don't think that I have messed up the widgets, but maybe it should be tested running a model on a Horus with all the bells and whistles.
I am aware that this is a pretty big commit from a guy with a short track record. Please let me know what else I can do to help validating it.

### CODE REVIEW

**Comment by lshems** [comment]
I would be happy to test on colour LCD.
Is there a firmware for jumper tx t16 that I can use, and a nightly or compiled companion?

**Comment by 3djc** [comment]
Without considering at all if we would want to do something like that, nor its technical implementation, I believe this is not the type of changes suited for a minor release

**Comment by jfrickmann** [comment]
> I would be happy to test on colour LCD.
> Is there a firmware for jumper tx t16 that I can use, and a nightly or compiled companion?

That would be great! I had problems when I tried building firmware for X10 though, as some python script is crashing. I can build the simulator w/o problems. Here is the error that I get:
```
[ 23%] Generating datacopy.cpp
  File "/opentx/opentx/radio/util/generate_datacopy.py", line 50
    print("Warning more than one union member (%s) in anynomous union inside struct %s, consider NOBACKUP statements" % (uc.spelling, cursor.spelling), file=sys.stderr)

                              ^
SyntaxError: invalid syntax
etc.
```
If someone can please help me solve that, then I will be right at it!
I used the following cmake options: -DLUA=YES -DTRACE_SIMPGMSPACE=OFF -DPCB=X10 -DPCBREV=T16

**Comment by jfrickmann** [comment]
> Without considering at all if we would want to do something like that, nor its technical implementation, I believe this is not the type of changes suited for a minor release

We could push it to 2.4 to have some more time for review. I made this request for 2.3, because that is what I forked from, and it cannot merge automatically into 2.4. But I have had it running for about 3 hrs (2 hrs flying) on my X9D+ and 1 hr (½ hr flying) on a TX12 without any issues, so I feel pretty good about it.

If you are interested, maybe we can set up a Skype or Zoom meeting and do some code review together? That could ease the process.

Whether we want to do something like this? Well, I hope that the Core Team will consider the opinions of the "script hacker community" with people like myself and l shems. I obviously want it, and I expect that other script hackers tend to agree. I also do not see what the downside would be. The CPU limit was obviously introduced to prevent scripts from blocking or delaying the perMain loop. This has now been solved by prempting the scripts instead, without adding much if any to the resource demand. So why not?

**Comment by jfrickmann** [comment]
I could also present the idea at the RCGroups thread about OpenTX 2.3, to see what kind of feedback we could get from people there - what do you say?

**Comment by bsongis** [comment]
Interesting idea, but I want we release 2.3.11 first!

**Comment by bsongis** [comment]
What about merging this one in 2.4?

**Comment by jfrickmann** [comment]
> What about merging this one in 2.4?

That would be great! And it would also allow for more time to test and validate. I only requested the pull into 2.3 because that is where I forked from, and it could not merge automatically with 2.4.

Please let me know if there is anything that I can do to help with the process!

**Comment by MRC3742** [comment]
> 
> That would be great! I had problems when I tried building firmware for X10 though, as some python script is crashing. I can build the simulator w/o problems. Here is the error that I get:
> 
> ```
> [ 23%] Generating datacopy.cpp
>   File "/opentx/opentx/radio/util/generate_datacopy.py", line 50
>     print("Warning more than one union member (%s) in anynomous union inside struct %s, consider NOBACKUP statements" % (uc.spelling, cursor.spelling), file=sys.stderr)
> 
>                               ^
> SyntaxError: invalid syntax
> etc.
> ```
> 
> If someone can please help me solve that, then I will be right at it!
> I used the following cmake options: -DLUA=YES -DTRACE_SIMPGMSPACE=OFF -DPCB=X10 -DPCBREV=T16

@jfrickmann Are you building in Windows?
I had a similar problem almost a year ago and helped draft the current documentation.
https://github.com/opentx/opentx/wiki/OpenTX-2.3-Windows-Build-Instructions
Especially follow Section 5: Install Python packages with PIP
"pip install pillow clang pyqt5"

Hope that helps - Rich

**Comment by jfrickmann** [comment]
@MRC3742, I build it in Docker with the image that you provide in the instructions for Linux. I run it under Ubuntu and wsl2 on a Windows machine. I just tried the pip command while running the docker image, and got:
```
Requirement already satisfied: pillow in /usr/lib/python2.7/dist-packages
Collecting clang
  Downloading https://files.pythonhosted.org/packages/ee/9b/2f0594be271803247d95e27c7135fe588c722b57624230b30b47f246184e/clang-11.0.tar.gz
Collecting pyqt5
  Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
```
Then I ran "make firmware" again, and the same error happened as described above.
If I comment out the ", file=sys.stderr" part, then I end up with:
```
  File "/opentx/opentx/radio/util/generate_datacopy.py", line 4, in <module>
    import clang.cindex
ImportError: No module named clang.cindex
```
Thanks!
Jesper

**Comment by MRC3742** [comment]
Sorry I couldn't be more help as I've never built with Docker.
You might try to use a newer version of python. I believe all current builds use the python3 commands.
Look through the requirements for the Travis builds https://github.com/opentx/opentx/blob/2.3/.travis.yml

Maybe someone with more knowledge using Docker could chime in - Rich

**Comment by jfrickmann** [comment]
@lshems - here is a T16 firmware file for you to test!
https://github.com/jfrickmann/SoarOTX/raw/master/wiki/media/firmware.bin 

@MRC3742 - it had to do with the Docker image running python 2.7 by default. Here is what I did.
- rm /usr/bin/python
- ln /usr/bin/python3 /usr/bin/python
- apt-get install python3-pip
- apt-get install python3-setuptools
- apt-get install clang-7
- apt-get install python-clang-7
- python3 -m pip install pillow clang

I will verify and incorporate the changes in a new Dockerfile for you later.

Thanks!
Jesper

**Comment by jfrickmann** [comment]
@MRC3742 - here is my modified Docker file. I just built firmware and simulator for X9D+ and T16, and it worked w/o problems.
```
# A Debian image for compiling OpenTX 2.2

FROM debian:stretch

RUN DEBIAN_FRONTEND=noninteractive apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake gcc git lib32ncurses5 lib32z1 libfox-1.6-dev libsdl1.2-dev \
      qt5-default qtmultimedia5-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev software-properties-common wget zip python-pip python-pil \
      libgtest-dev python3-pip python3-setuptools clang-7 python-clang-7
      
RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN python -m pip install filelock pillow clang

RUN wget -q https://launchpad.net/gcc-arm-embedded/4.7/4.7-2013-q3-update/+download/gcc-arm-none-eabi-4_7-2013q3-20130916-linux.tar.bz2 && \
    tar xjf gcc-arm-none-eabi-4_7-2013q3-20130916-linux.tar.bz2 && \
    mv gcc-arm-none-eabi-4_7-2013q3 /opt/gcc-arm-none-eabi

VOLUME ["/opentx"]

ENV PATH $PATH:/opt/gcc-arm-none-eabi/bin:/opentx/code/radio/util

ARG OPENTX_VERSION_SUFFIX=
ENV OPENTX_VERSION_SUFFIX ${OPENTX_VERSION_SUFFIX}

ENTRYPOINT ["bash", "-i"]
```

**Comment by lshems** [comment]
> @lshems - here is a T16 firmware file for you to test!
> https://github.com/jfrickmann/SoarOTX/raw/master/wiki/media/firmware.bin
> 
> @MRC3742 - it had to do with the Docker image running python 2.7 by default. Here is what I did.
> 
> * rm /usr/bin/python
> * ln /usr/bin/python3 /usr/bin/python
> * apt-get install python3-pip
> * apt-get install python3-setuptools
> * apt-get install clang-7
> * apt-get install python-clang-7
> * python3 -m pip install pillow clang
> 
> I will verify and incorporate the changes in a new Dockerfile for you later.
> 
> Thanks!
> Jesper

I'll check it out.

**Comment by lshems** [comment]
OK, Bootloader and firmware install from SDcard work. Radio works. Seems more stable and quicker in executing scripts, but i may just want to see that.

Tested with a very heavy graphing app, storing multiple graphs in memory and displaying the selected one actively running. Runs fine and smooth, with the custom model setup gui in a second widget in parallel.

When running another app, with a known bug on my side (or at least I know it crashes predictably) it correctly enters emergency mode.

Looks GOOD!

will leave the radio running for some time now

**Comment by jfrickmann** [comment]
Great, thanks for the report lshems!

**Comment by lshems** [comment]
Just a stupid question, where do I find the LUA reference guides??

**Comment by jfrickmann** [comment]
> Just a stupid question, where do I find the LUA reference guides??

There are no stupid questions :-)
Some things are missing or broken in the 2.3 guide: https://opentx.gitbooks.io/opentx-2-3-lua-reference-guide/content/
So I often use the 2.2 guide: https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/

If the Core Team would like some help maintaining the reference guides, then I will hereby volunteer to help out!

**Comment by kilrah** [comment]
> If the Core Team would like some help maintaining the reference guides, then I will hereby volunteer to help out!

You should now have access to https://github.com/opentx/lua-reference-guide :)

**Comment by lshems** [comment]
Ok. Radio looks stable. See graph of radio voltage.

Running as onetime script gives some problems:
See error in screenshot when navigating around in my menu.
I'll check if it also crashes as a widget.

**Comment by lshems** [comment]
It is stable as a widget, only crashes as a onetime script.

Since the widgets I use, are just a repackaging of callls to the telemetry script, there is something wrong on the standalone lua script handling.

Might even be there before the introduction of the change. So I would need to test with a 2.3.11 firmware.

Tomorrow :)

**Comment by jfrickmann** [comment]
> It is stable as a widget, only crashes as a onetime script.
> 
> Since the widgets I use, are just a repackaging of callls to the telemetry script, there is something wrong on the standalone lua script handling.
> 
> Might even be there before the introduction of the change. So I would need to test with a 2.3.11 firmware.
> 
> Tomorrow :)

lshems, are you able to share the script that crashes? I would like to figure out what happens. It sounds like it calls an API function which then calls Lua. But AFAIK, all API functions just return to Lua, so I don't understand what happens here.
Thanks!

**Comment by raphaelcoeffic** [comment]
@jfrickmann hi Jesper! As you were suggesting adding this to 2.4, I’d suggest moving this to EdgeTX, as this where 2.4 dev takes place. That would fit perfectly with the new capabilities given to LUA widgets now.

**Comment by 3djc** [comment]
@lshems @jfrickmann Can we get  to the bottom of the 'one time' issue so this gets moved forward ?

**Comment by lshems** [comment]
I'll check this evening. Didn't see the posts. Sorry.

**Pull request closed without merging**
