### PR TITLE
Qba667/nv14merge

### PR DESCRIPTION
**Pull request by qba667**
Hardware support for NV14 merged.

### CODE REVIEW

**Comment by kilrah** [comment]
Would like to have a look but it seems a file is missing 

CMake Error at radio/src/CMakeLists.txt:539 (add_executable):
  Cannot find source file:

    targets/nv14/extmodule_helper.cpp

**Comment by qba667** [comment]
@kilrah missing file committed.

**Comment by derdoktor667** [comment]
...hello, is this the "active" working branch for upcoming NV14 support in 2.4? ...NV14 fell out of the actual "2.4" branch and nothing to see about it anymore

best regards

**Comment by kilrah** [comment]
Yes.

**Pull request closed without merging**
