### PR TITLE
Allow minimizing the telemetry simulator window when un-docked.

### PR DESCRIPTION
**Pull request by mpaperno**
**Needs testing on Mac and Linux.**  Incomplete tag until tested.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Minimising works on Mac, but then I cannot resize the dialog anymore, which is quite a pain. Docking does not work anymore either.

**Comment by mpaperno** [comment]
Can't resize which dialog?

Are you sure docking doesn't work?  You can dock by dbl-click on the title bar.  If you drag-to-dock then there needs to be enough space available in the main window, otherwise it won't show any available drop locations.

But maybe indeed this breaks it on Mac...

**Comment by raphaelcoeffic** [comment]
@mpaperno the telemetry simulator dialog (or whatever this is). Concerning docking, you're right, still works, I just have to use the right thing! (double click)

**Comment by mpaperno** [comment]
You mean it's no longer resizable when non-minimized?  At all, or until it's minimized the first time?

**Comment by raphaelcoeffic** [comment]
neither nor.

**Comment by mpaperno** [comment]
I think this is no longer necessary now that the telem. sim window can just be hidden w/out interrupting telemetry.

**Pull request closed without merging**
