### PR TITLE
Mixers Monitor in the simulator

### PR DESCRIPTION
**Pull request by davxlw**
I had forgotten the simulator...

### CODE REVIEW

**Comment by bsongis** [comment]
Hmm. no, I will have a lot of emails if I accept it!!!

**Comment by davxlw** [comment]
Ok, I'll remove it but, could the simulator reflect the build options chosen in Companion ?

**Comment by bsongis** [comment]
Yes it's possible, but a lot of work, we need to support DLLs / .so etc. which would be built on the compilation server just like our firmwares!

**Comment by davxlw** [comment]
Couldn't be possible to build the simulator with all the options, and activate them at run time relative to the build options set in the profile settings ?

**Comment by bsongis** [comment]
But you noticed that those options are compile options!

**Comment by davxlw** [comment]
Yes, I tend to forget the close link between firmware and companion (and so simulator)...

**Pull request closed without merging**
