### PR TITLE
Fix the special character problem for ö,ü,ä in german

### PR DESCRIPTION
**Pull request by loetefix**
There is still a problem with ä , ö , ü when crate a new model. these changes fix the problem,

tested on T16, Horus and XLITE

### CODE REVIEW

**Comment by bsongis** [comment]
What is the issue you want to fix? Logs on SD? On which radio?

**Comment by loetefix** [comment]
When you create a new model in german the stick Höh (ELE) is shown as H8h. In all radios.

**Comment by loetefix** [comment]
The change in strhelpers will fix it.

**Comment by 3djc** [comment]
This is 2.3.5

image

**Comment by loetefix** [comment]
Created with wizzard or without?

**Comment by 3djc** [comment]
without, and the wizard in english only, so would not exhibit that issue anyway

**Comment by bsongis** [comment]
@loetefix you had the issue with the wizard? I remember of a fix I did some months ago on this topic, are you sure you have the very last wizard lua scripts?

**Comment by 3djc** [comment]
Created with wizard

image

**Comment by loetefix** [comment]
No. Not with wizard. I am confused. A friend habe same problem

**Comment by kilrah** [comment]
@loetefix Did you transfer that model into companion and back to the radio?

**Comment by loetefix** [comment]
No. When i create a new model in the transmitter, the höh appears allways as H8h.  This evening i will try it again.I have no wizzards on sd card, because i dont use it

**Comment by kilrah** [comment]
Then can't reproduce it here with 2.3.5. Transfer to companion and back will break special chars in names though, that's known.

**Comment by loetefix** [comment]
Hi, today i loaded the 2.3.5 on a taranis x7. I created a new model with wizard on the taranis and then there ist also H8h instead Höh. (Not created on companion)

**Comment by 3djc** [comment]
What wizard did you use ? The one on our pack ?

**Comment by loetefix** [comment]
Yes, from the sd card content. The same problem is when create a model without wizard

**Comment by 3djc** [comment]
Well just above you said with wizard. Is it with or without ?

**Comment by kilrah** [comment]
Do you have anything configured in Radio/Hardware for the custom names of the sticks?

**Comment by loetefix** [comment]
No i have not configured custom names and it is with and without wizard. Tomorrow i can make a youtube video.

**Comment by loetefix** [comment]
https://fpv-community.de/threads/jumper-t16.84369/page-75#post-1047064

There are some people they have the same issue.

**Comment by kilrah** [comment]
Ref. #6581

**Comment by Xillius178** [comment]
On an color screen aka Horus, Jumper T16 or Radiomaster TX16S i have no Problem with this german Vowels...


The problem is more likely that the old displays from Taranis etc.

These cannot be shown internally in the display controller.
Since the character sets are not available in this.

**Pull request closed without merging**
