### PR TITLE
Fix to many failsafe channels editable when less then "1 column (8)" …

### PR DESCRIPTION
**Pull request by RealTadango**
…of channels is used

### CODE REVIEW

**Comment by mpaperno** [comment]
OK I see the issue on Horus screen with extra channel showing up in the right column.  But not on 212x64.  Can you post a screenshot?  Thanks.

**Comment by RealTadango** [comment]
I only checked the code for all guis and it looked like the same issue (also a double loop). I have not tested it on other devices.

**Comment by 3djc** [comment]
Same here, cannot reproduce on x9. A LOT of wo work as gone into making the simu available and working, please make sure at least some level of testing is done, even if you do not own the physical radio

**Comment by mpaperno** [comment]
On the smaller screen it properly set the number of columns already.  Fixed, thanks for reporting.

**Pull request closed without merging**
