### PR TITLE
Fix T16 calibration image in dark blue theme

### PR DESCRIPTION
**Pull request by benlye**

### CODE REVIEW

**Comment by benlye** [comment]
Here's a version of t16.bmp with transparency, which looks a little nicer than the one with the white background when used with the dark blue theme.

IMG_20191223_090903 (Medium)

[t16.zip](https://github.com/opentx/opentx/files/3994295/t16.zip)

**Comment by 3djc** [comment]
Could you include it to your PR ?

**Comment by benlye** [comment]
Sorry, yes - I didn't realize that the SD card files were in the repo as well.  Should have looked first!

Just added it.

**Comment by 3djc** [comment]
👍

**Pull request merged**
