### PR TITLE
Also backup members inside unions,

### PR DESCRIPTION
**Pull request by schwabe**
the code is a bit more complicated since unions can have structs or simple types.

### CODE REVIEW

**Comment by schwabe** [comment]
sorry, my mistake with last minute changes, will upload a fixed version

**Comment by schwabe** [comment]
Whatever caused that build to fail it was not my commit.

**Comment by kilrah** [comment]
The "Details" link is there for a reason ;) Travis failed because some server it needs to pull stuff from seems to be down so it can't configure itself.

**Comment by schwabe** [comment]
I see that you reverted the pull request again, is there anything wrong with it that I can fix?

**Pull request merged**
