### PR TITLE
Bsongis/issue2595 cli

### PR DESCRIPTION
**Pull request by bsongis**
It works here, and the USB serial works perfectly as well (Debian Stretch)

### CODE REVIEW

**Comment by projectkk2glider** [comment]
I am still missing a check for the "fullness" of USB TX buffer. You should stop printing chars from CLI thread and wait some time before continuing if TX buffer is full.

**Comment by bsongis** [comment]
I think it could be inside the driver, not the cli!

**Comment by bsongis** [comment]
exactly as it is done here:
void serial2Putc(const char c)

**Comment by projectkk2glider** [comment]
I agree.

**Comment by projectkk2glider** [comment]
Something is not right. This command stalls the CLI output:
```
print 0x20000fe6 200
```

I guess when the out buffer (512 bytes) is filled the check inside usbSerialPutc() goes into infinite loop.

**Comment by projectkk2glider** [comment]
I've got it, fix coming soon...

**Pull request merged**
