### PR TITLE
Document values of UNIT in the function describtion

### PR DESCRIPTION
**Pull request by schwabe**
Is is a bit a less clean than pull request #3990 but has no additional memory requirement

### CODE REVIEW

**Comment by bsongis** [comment]
This one is already merged, no?

**Comment by schwabe** [comment]
This one only adds the documentation for Taranis which does not have the constants

**Comment by bsongis** [comment]
I am afraid someone else included your mods in another PR, am I right?

**Comment by schwabe** [comment]
Yea, it is @floaledm included that. Did not see that.

**Pull request closed without merging**
