### PR TITLE
Bsongis/issue 1925 screenshots on taranis

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

**Comment by bsongis** [comment]
No comment? Let's merge it then!

**Comment by projectkk2glider** [comment]
Just tested in simulator, works excellent :+1: 

We just need to remind users to create SCREENSHOTS directory otherwise this won't work.

**Comment by bsongis** [comment]
Normally no, it should be automatically created, just as [MODELS] or [LOGS]

**Comment by projectkk2glider** [comment]
You are right, the problem is in simulator which does not return proper error on missing dir. Then the missing dir is not created. But as you say it should work on the radio.

**Comment by projectkk2glider** [comment]
It will also work on simulator when #2093 is merged!

**Pull request merged**
