### PR TITLE
Filter out hidden and system files

### PR DESCRIPTION
**Pull request by 3djc**
This should help #4589

### CODE REVIEW

**Comment by projectkk2glider** [comment]
I agree with this change. But I am wondering what is your rationale why would this help/prevent a crash?

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/issues/4589#issuecomment-286313662

**Comment by projectkk2glider** [comment]
Sure, but **why** did those files cause a crash and what needs to be fixed so another file does not produce the same issue.

**Comment by 3djc** [comment]
It is more that given the wide range of OS and image utilities that may create all kinds of thumbnails, it sounded to me like a good thing to do no matter what.

**Comment by bsongis** [comment]
It doesn't fix the issue, but it won't hurt!

**Pull request merged**
