### PR TITLE
Allow R9M 2019 in ACCESS mode on some radios

### PR DESCRIPTION
**Pull request by 3djc**
Initial idea and some mod photo and some code taken from cvetaevvitaliy.

This enables full support for R9M 2019 in ACCESS mode, including OTA updates.

Currently supported radio: Radiomaster TX16S, Jumper T16 and T18, FrSky X10, X12S

Hardware mod details : https://github.com/opentx/opentx/wiki/Externalaccessmod

X9D(+), X7 (without BT) should be possible too, but needs people to test and document successfull hardware mod

### CODE REVIEW

**Comment by brainbubblersbest** [comment]
Hello @3djc ,
**_1._**
in companion/src/firmwares/opentx/opentxinterface.cpp @49471d5
i noticed you add the option ExternalAccess to x10_Express Boards. (Line 1240)
ExpressX10Boards have this Function already and dont need this Option

But we need this for the X10 non Express Boards (like the Internalaccess option in Line 1234)
And i would appreciate an Externalaccess option for the X12 non ExpressBoard (like the Internalaccess option in Line 1248)
I´m a very bad coder, so if i missunderstand your commits, i really apologize for that.

**_2._**
In radio/src/targets/horus/hal.h @d39d70f
**If i understand the Code right, shouldnt be the lines 786-814 placed under the Definition at line 405** 
#if defined(PCBX12S) || defined(RADIO_TX16S) && !defined(EXTERNAL_ACCESS_MOD)

**Or as an alternative change the Definition at line 405** 
#if defined(PCBX12S) || defined(RADIO_TX16S) && !defined(EXTERNAL_ACCESS_MOD)
back to
#if defined(PCBX12S) || defined(RADIO_TX16S)
**the aux_serial definitions should be not true if && defined(EXTERNAL_ACCESS_MOD) or defined(PCBREV_EXPRESS)
Because the Pins, timers, etc used for aux_serial (not aux2_serial) need to be free for external_module wiring.
maybe the aux_serial definitions, can be moved to the position after the definitions from line 785 with a elif?**
and 
**for align the needed definitions**

**change the line at785**
#if defined(PCBX10) && defined(PCBREV_EXPRESS) || defined(EXTERNAL_ACCESS_MOD)
 to
#if defined(PCBX10) || defined(PCBX12S) || defined(RADIO_TX16S) && defined(PCBREV_EXPRESS) || 
 defined(EXTERNAL_ACCESS_MOD)

**to align the External Module definitions , Timers, and Pins to the Firmware Option for the X12, x10 and TX16S?**

also,
**_3._**
 in radio/src/trainer.cpp @3739793
The Mod on Horus dont Bridges the HB, used by FRSKY internal HF Hardware and RX Module Pins, 
when the Mod is done like in the Wiki. 
**Resistor "R1" is not Build in from Factory.**

_Maybe im wrong, i still learn alot and just want to help ;-)_.
Edit: now i realised that the.  !   Is a negate marker wich makes way more sense now.

**Comment by brainbubblersbest** [comment]
Is the hal.h now changed in line 785.? 
Pb.10 and pb.11 are still not defined for pcbx12s.
And so arent The tim2, the chan3 and the other Things belong to uart3.
Or how is that Code used?

**Comment by skorokithakis** [comment]
Clarifying question that I plan to add to the wiki, does the hardware mod adversely affect ACCST mode or anything else? I'd like to mod my radio in preparation, since this PR was merged.

**Comment by brainbubblersbest** [comment]
> Clarifying question that I plan to add to the wiki, does the hardware mod adversely affect ACCST mode or anything else? I'd like to mod my radio in preparation, since this PR was merged.
For Jumper and Radiomaster its working.

The Horus Inverter Board Wiki isnt complete till Today. 18.10.2020
If its done like in the Wiki. Old R9M will not work.
It need a little change in addition. 
-Maybe one or two extra resistors soldered to the Board 1 cables.
-Or it can be enough just not to solder the 3,3v supply for the Board 1 
But i cant test this not before wednesday, maybe i find a few minutes today.

Presolder any of the MODS will not affect the Transmitter. 
If you flash without the ExternalaccessMod Option, then OTX drive simply the old traces.

**Comment by skorokithakis** [comment]
> If its done like in the Wiki. Old R9M will not work.

Sorry, I'm confused, later on you say:

> Presolder any of the MODS will not affect the Transmitter.

Or did you mean it will affect the Horus but not the Jumper/RadioMaster?

**Comment by 3djc** [comment]
On Radiomaster or Jumper, there is absolutely no side effect.

On X10S, X12S, there is hope that it will work with no side effect, but currently, it brakes other external modules

**Comment by skorokithakis** [comment]
Thanks, I'll add it to the wiki!

**Comment by brainbubblersbest** [comment]
Forget what i deleted. Im testing it right now with all modules.

**Comment by P-I-Engineer** [comment]
would this work if you put an isrm radio board into a X10 module bay? Or is this only for R9?

**Comment by 3djc** [comment]
Only r9, isrm external module are not sold anyway

**Comment by P-I-Engineer** [comment]
https://www.horusrc.com/en/frsky-access-taranis-x9-lite-s-rf-board.html

x9 lite rf board?

**Comment by brainbubblersbest** [comment]
> Thanks, I'll add it to the wiki!

It's working now with all modules. 
You can Update the Wiki. I posted New schema for x10 and x12 at the issue. This might be helpfull for Qx7 and maybe Qx9d also.

**Comment by dl1bg** [comment]
Tested the branch
https://github.com/cvetaevvitaliy/opentx/tree/RadiomasterTX16S_ACCESS
on my TX16S with R9M + R9MM, works.
THANK YOU VERY MUCH, I highly appreciate the more conveniant binding process and OTA without unsoldering my receiver.

Also tested 2.3.22N359, feature is not yet included. Looking forward to use the feature with the official 3.11.

Thanks again, good work!

**Comment by 3djc** [comment]
It is if you select externalaccessmod in companion nightly

**Comment by dengiskong** [comment]
Hello, I have a RadioKing TX18S. I did the hardware mod as the RadioKing board has identical components in the same placement as the Jumper T18. From everything I have seen, the RadioKing TX18S is the Jumper T18. I just got an R9M ACCESS module and receivers, so after completing the hardware mod, I flashed 2.3.11 opentx firmware with externalaccessmod through opentx companion and updated the TX18S's bootloader to 2.3.11 as well. I am getting no different options in my External RF menu on my model setup page - the options are still PPM, XJT, DSM2, CRSF, MULTI, R9M, GHST, SBUS, and AFHDS3. Hoping to get this working! Thanks for all the efforts put in!

**Comment by HonzaJaros** [comment]
Can the WIKI be edited? as I understand, from 2.3.11 firmware doesn't need to be flashed???  thanks

**Comment by 3djc** [comment]
???

**Comment by HonzaJaros** [comment]
in wiki of the mod is written:

`Note : this option is currently under development, and is not yet available at time of writing of this page. Availability is scheduled in 2.3.11 nightlies and 2.3.11 release.

This page is a reference guide for "externalaccessmod" for some supported radios. This mod allows you to use the FrSky R9M 2019 in ACCESS mode with the following radios. In addition to the hardware modification, a firmware with 'externalaccessmod' option needs to be flashed on the radio.`

So If I understand well, the 'externalaccessmod' is already included in 2.3.13, isn't it? 

just kindly asking if this page of wiki can be updated. :)

thanks

**Comment by 3djc** [comment]
No is an option that needs to be manually selected if hardware mod is done on those compatible radios. That hasn’t changed, and will not change since the hardware becomes different

**Comment by HonzaJaros** [comment]
that's ok, I understand, I am just pointing out that the wiki is outdated, isn't it? :)

**Comment by pskmac** [comment]
Is there anything else than flashing externalaccessmod and 3 cables soldered needed to make it work? I think i did all steps but got stuck and dont really know where to seek for help.

**Comment by skorokithakis** [comment]
I think you need four cables, actually.

**Comment by pskmac** [comment]
> I think you need four cables, actually.

Would you be that kind and say something more please ? Im rather amateur but with clear hints I can do that :).

Thanks for comment.

**Comment by skorokithakis** [comment]
Oh, it's shown in the photo but it's a bit unclear. You need to solder a fourth wire to the second pin of the module, IIRC. I'm on the phone right now so I can't look it up more, but if you notice the photo you'll see where the fourth wire goes, if I remember correctly.

**Comment by pskmac** [comment]
It may sound stupid - sorry, but where the end of that cable should be soldered to ?
So on that PCB where module is plugged in I should actually solder 2 cables into ?

**Comment by skorokithakis** [comment]
Hmm no, it looks like I'm misremembering, sorry. You only need TX/RX and 6V, nothing else... It should then just work. Have you flashed ACCESS and enabled that in the external module settings?

**Comment by pskmac** [comment]
Np - so I soldered 3 cables only as shown on the pictures and the only YT video that I have found. I soldered to the pin shown with red arrow, not like on the picture.
image

Yes, I have flashed openTX with enableaccessmod and I can pick R9M ACCESS from external modules - so I suppose it is flashed correctly. I also flashed 4in1 module with most up to date version and flashed R9M with most up to date ACCESS firmware.
image
image

When I click Register I keep having "waiting" message on the screen.
image

Red LED is solid on the module, while in register mode it is quickly blinking.

I must say it worked several times and found RX but it was like few %s of all tries. I really dont know what wrong I am doing.

**Comment by 3djc** [comment]
In version screen, push enter in Modules / RX version. That should report the r9m 2019 module details, that probably a lower level test than bindings

**Comment by pskmac** [comment]
When I do that (with R9 ACCESS enabled in Model Setup tab) under Version tab, it shows "---" on External Module.

**Comment by HonzaJaros** [comment]
I would not bother.

I was trying to do that as well, and then instead of soldering, i flashed ExpressLRS, problem solved…


 Honza

**Comment by pskmac** [comment]
You flashed it on both - receiver and R9M ?

**Comment by 3djc** [comment]
> You flashed it on both - receiver and R9M ?

Thats why I suggested to go to version, if he does not get it, then the rest won't work, it means the hardware mod is not ok likely

**Comment by pskmac** [comment]
Okay, thanks for comment.

To have it clear - it means that I did something wrong with wiring etc. ?

**Comment by pskmac** [comment]
... and TX i am using is R9 sx which does not seem to be supported by ExpressLRS

**Comment by pskmac** [comment]
Apologies for multiple posts.

I managed to take a photo of the mod and TX scree shot. I hope that helps to verify what is wrong.

130668216-69576057-d74e-4a5e-bd05-9a3e9d16facc
130668249-fb6a2541-32a6-40bd-9210-625b65d70ad6
130668264-46d1781b-db01-4dfa-a842-121fe6a85cbf
130668477-97cb54c8-44af-4874-861e-2c6357c277a9

**Comment by 3djc** [comment]
This is what you should get if your hardware mod is right

image

image

Itis probably a very old firmware displayed here since I have not updated this module for ages, but the principle stays, this is the best way to confirm a proper hardware mod

**Comment by pskmac** [comment]
Okay - thanks. 
But still I am not sure if I did something wrong with soldering itself - or there is something else I need to do on the software/firmware ? Please, advise.

**Comment by 3djc** [comment]
No software settings other than selecting R9M ACCESS module type and have the module inserted. You messed up your soldering more than likely

**Comment by pskmac** [comment]
I compared what I soldered with schemes on wiki and it seems like its done properly. Maybe solders itself is weak or something. Cannot see any other reason.

If I would flash ACCST soft onto R9M, select standard R9M FCC/LBT from model setup -  then should it be visible in modules / rx version tab, I mean information about external module (standard R9M) ? Im just trying to find out whether the module itself is not working properly - instead of blaming soldering (what is possible tho ofc).

**Comment by 3djc** [comment]
No, only access modules (and multimodules) report their version

**Comment by HonzaJaros** [comment]
I am afraid that you unfortunately messed up those transistors :(

According to those pictures you have taken. I would say so 


 Honza

**Comment by pskmac** [comment]
Okay - thanks for your support folks. You might be right Jan, I am not experienced solderer, it looked basically like a simple mod so I gave it a try. 
I hope I did not destroy my radio and I will be able to use with standard ACCST.

I think I will drop idea of externalaccessmod on my TX16s, switch to RX supporting ACCST and flash my R9M2019 with ACCST or switch to RX which is supported by ExpressLRS.

It looks like I cannot dig anything more out of R9 SX in terms on TX16 + R9M.

**Comment by brainbubblersbest** [comment]
Yeah. Looks like a lot of heat. Too thick wires. Too big solder iron.

**Comment by pskmac** [comment]
Thanks for comments.

Can it be fixed or should I drop that idea?

Radio should work fine, shouldn't it? Should I get rid of cables?

I hope I did not mess it up that far that I would not be able to use r9m
accst or elrs.

M

śr., 25 sie 2021, 15:16 użytkownik brainbubblersbest <
***@***.***> napisał:

**Comment by brainbubblersbest** [comment]
If not. You can solder in the frsky inverter mod from the x10 to fix it. Works the same way. And in case you Fried a inverter from pin1. You get your Radio working again.

I think it's anyway User friendlier. Because it's not needed to solder on the Mainboard Transistors. Only on solder holes/points.

**Pull request merged**
