### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by LapinFou**

### CODE REVIEW

**Comment by LapinFou** [comment]
FYI, there is an extra space between _X7_ and _/_ in the field **"FrSky Taranis X7  / X7S"**.
The concerneed file is *../firmwares/opentx/opentxinterface.cpp* line 1224
I don't know if it is done in purpose.

**Comment by 3djc** [comment]
I probably made a typo, will check it

**Comment by 3djc** [comment]
Fixed :)

**Comment by LapinFou** [comment]
Nice!! 😄 
That was fast!! 👍

**Pull request merged**
