### PR TITLE
Next

### PR DESCRIPTION
**Pull request by jermoo**
initial pull ... base fork: opentx/opentx base: master .. head fork: jermoo/opentx compare: next

### CODE REVIEW

**Comment by kilrah** [comment]
Hmm shouldn't that be opened against next instead of master? What is it in the first place?

**Comment by projectkk2glider** [comment]
Hi @jermoo, this pull makes no sense, closing. You are trying to merge the `next` branch into the `master` branch.

Short explanation:
* `master` branch holds 2.0.x development, currently it contains a development that will eventually produce a 2.0.16 version.
* `next` branch holds 2.1.x development which has no releases yet.

Example workflow if you want yo add some feature or fix a bug on 2.0.15 version:
* get up to the last commit on the `master` branch (git pull)
* create a new branch based on `master` branch and give it a meaningful name 
* add your changes (commits) with useful commit comments (you can reference issues by including their numer in commit message).
* after you are satisfied with your work and have tested it, you create a new pull request from your branch against the opentx`master` branch.
* we will then look at your pull request, add some comments if needed and eventually merege it into the master branch.

More info in wiki: https://github.com/opentx/opentx/wiki/Github-issue-workflow and https://github.com/opentx/opentx/wiki/OpenTX-Developer-Guide (this page is not finished)

**Comment by jermoo** [comment]
@projectkk2glider , Bsongis told me to do a pull so I can be added to the project. I don't know what I'm doing with Github as i'm new. I thought I was only pulling to my repository. I need to find the explaination on what GitHub is actually doing. I'll read the links you provided but I believe I've already seen it (maybe not).
Jer

**Comment by projectkk2glider** [comment]
I see now, this was just a way for Bertrand to see who you are on github. I hope you get added soon to the OpenTX team.

**Comment by bsongis** [comment]
Not exactly, I prefer adding members once I am sure they have started messing with git (as everybody did including me) before they start commiting here. 
So I propose @jermoo to do anything he wants (an open issue, a new sexy feature, a translation, whatever useful for the community...) and open a pull request, once the process completely done I add him to the project.

**Comment by projectkk2glider** [comment]
@bsongis you have a point there.

**Pull request closed without merging**
