### PR TITLE
SE updates and in sync with en #3113

### PR DESCRIPTION
**Pull request by HakanBastedt**
An attempt to push updates to the SE translation.

### CODE REVIEW

**Comment by bsongis** [comment]
Perhaps you will like to merge it on the 'next' branch then?

**Comment by bsongis** [comment]
I added CRSF protocol there last week if I am not mistaken, perhaps it won't be better

**Comment by bsongis** [comment]
I let you reopen the pull request once ready, ok?

**Comment by HakanBastedt** [comment]
I don't really know what "reopen the pull request means", sorry.
But I had a look, and there where just a few changes needed in se.h.txt in the "next" branch.
I have the changes here, shall I do a new pull request?

**Comment by projectkk2glider** [comment]
You could add a new commit to this branch and press the `Reopen and comment` button **OR** you can create a new pull request.

Do you see the  `Reopen and comment` button below? Perhaps not. 
screenshot

**Comment by HakanBastedt** [comment]
No, I don't have the left button. I have created a pull request now.

With this update both master and next should have the SE translation up-to-date.

**Pull request closed without merging**
