### PR TITLE
DIY ID range changed to 0x5100 - 0x52FF 

### PR DESCRIPTION
**Pull request by projectkk2glider**
(according to SPORT specification V3.4.0)

### CODE REVIEW

**Comment by bsongis** [comment]
I asked for confirmation, this will break Craft & Theory converter for Ardupilot!

**Comment by floaledm** [comment]
Thanks Bertrand. Unfortunately, this would be quite disruptive to users of Passthrough on ArduPilot. That includes our own users but also other projects using Passthrough on ArduPilot (e.g., ersky9x: http://openrcforums.com/forum/viewtopic.php?f=95&t=9164).

The FrSky forum appears to be down so I can't look at the spec. Could the range simply be changed to 0x5000 -0x52FF?

By the way, the luadoc for sportTelemetryPop() would also need to be updated to reflect the new range.

**Comment by 3djc** [comment]
The official range from FrSky:
image

**Comment by projectkk2glider** [comment]
@floaledm try to convince FrSky to change the range. We can change the range of DIY in OpenTX no problem, the only problem would be if FrSky produces some sensor that uses range from 0x500 fo 0x5ff.

**Comment by bsongis** [comment]
Email sent

**Comment by floaledm** [comment]
Thanks Bertrand! I think you'll be more convincing that I ever would...

Damjan's argument is definitely valid, so it would be good to clear this out. So, you guys don't know the reason behind the change? Does FrSky sometimes do this, and then you just have to play catch-up?

**Comment by bsongis** [comment]
No the error is mine, I asked for a wrong range (or I gave you a wrong ID)

**Comment by bsongis** [comment]
FrSky will update the S.PORT spec, DIY range will be 0x5000-0x52ff

**Pull request merged**
