### PR TITLE
[X10S] PWM sticks support - with autodetection

### PR DESCRIPTION
**Pull request by bsongis**
Review and comments appreciated!

### CODE REVIEW

**Comment by 3djc** [comment]
Hardware tested x9e,  no issue

**Comment by bsongis** [comment]
it remains that sticks are inverted

**Comment by schwabe** [comment]
@bsongis I can spend some time polishing @3djc and my approach to learn stick direction while doing hw calibration to make it ready to include in normal OpenTX.

We could then always do the STick direction detecting on X10 and optionally on the other remotes

**Comment by bsongis** [comment]
It's not needed here, but why not!

**Pull request merged**
