### PR TITLE
Add TBS Crossfire lua scripts for X7 SDCard

### PR DESCRIPTION
**Pull request by OhmEye**
I edited the scripts for X9D to change the input events for the rotary wheel and the drawing coordinates for the smaller LCD. Tested by a handful of volunteers and myself on X7's with working CRSF.

### CODE REVIEW

**Comment by techsavvyfpv** [comment]
Yes the lua script works great on the X7.

**Comment by thongraegu** [comment]
Didnt work on my QX7 EU version if that matters, just gets stuck on Waiting For Crossfire.

**Comment by bsongis** [comment]
👍

**Comment by OhmEye** [comment]
@thongraegu Does your X7 have working CRSF telemetry? The lua script must have CRSF telemetry working to talk to the devices. #4922

**Comment by thongraegu** [comment]
@OhmEye I see I see yeah it doesnt work currently, havent done any mods for my X7 yet.

**Comment by nathanielakkermans** [comment]
@OhmEye very nice work! your script is working perfectly on my QX7 EU, thank you!

**Comment by OhmEye** [comment]
I want to be slightly pedantic here and point out I didn't write the script. :) An analogy would be that somebody else designed, tailored, sewed, and sold a pair of pants and all I did was adjust the hem for a different height. :) I created nothing, I just changed some event codes and numbers for the screen size.

**Comment by madwasp** [comment]
Hello, I know that this topic is not new but I was not able to find the answer anywhere yet.

I've a Taranis Q X7 and a TBS Crossfire Micro TX and I'm not able to run the lua scripts.
It always gives me the "Waiting for Crossfire devices..." message.

I've done the inverter mod and also I've tested the new crossfire.lua and device.lua scripts but the situation is the same.

Any idea how can fix this? 

Really appreciate your help.

**Comment by FPVpat** [comment]
@madwasp I was having the exact same issue as you. Spent a few hours trying to resolve. I was able to get the lua script working by updating my micro tx crossfire module to the newest version (v2.11). See the TBS website for instructions on how to update the crossfire. You may need to select "Include unstable releases" in TBS Agent to see this version. Hope this helps.

**Comment by josh-kenny** [comment]
hi there, I just got a brand new crossfire micro and im unable to execute the lua script to get set up. I dont get any waiting messages, or errors, it just kicks me back to the folder contents screen. Ill note that I have completed the X7 hardware mod, have bound up the RX and am not receiving the constant telemetry warning errors, which leads me to believe my mod was successful. Any idea why the lua script would fail?

**Pull request merged**
