### PR TITLE
Taranis Q X7 optimized wizard

### PR DESCRIPTION
**Pull request by NiklasVoigt**
I redesigned the wizard for the X7!

Check this out:
https://www.youtube.com/watch?v=86H1YKcVyB4

After the implementation of issue #5069 drawbitmap will be implemented too! :-)

### CODE REVIEW

**Comment by 3djc** [comment]
Quite nice. There seems to be an issue when the drop down and other text :
image

**Comment by NiklasVoigt** [comment]
Fixed :-)

**Comment by 3djc** [comment]
Yes, much nicer :). I think the botttom wiz botttom line should go away (the ModWiz...), and since we do not have heli, maybe that should not be looking like an option too (remove since there is not way to 'grey out' ?)

**Comment by NiklasVoigt** [comment]
That sound good! I've removed the bottom bar and uncommented heli (since there is not way to 'grey out' ) for easier implementing in the future. :-)

**Comment by mythreeleggedcat** [comment]
Just tried this on 2.2.  Still testing it but good job!  One issue I noticed is the final Long Press Enter to save the model always brings up the Backup|Copy|Move menu which you then have to dismiss!

**Comment by RCdiy** [comment]
@NiklasVoigt could you help me get this set up prior to 2.2.1 release.... I'd like to document it...

**Comment by schwabe** [comment]
@RCdiy it is part of the nightly builds (+nightly sdcard contents)

**Comment by RCdiy** [comment]
@NiklasVoigt 
What is GV Use:
It shows up when Menu is long pressed
How does one remove it once it shows up
screenshot_x7_17-10-12_12-11-39

**Comment by Mikey1968** [comment]
You should add retracts as well , Not remember if the flaps were there as well

**Pull request merged**
