### PR TITLE
X-Lite PWM sticks

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

**Comment by 3djc** [comment]
@bsongis version "BIND broken on X-Line (and X7?)" does not allow X7 to bind (for both int and ext module, pushing bind does nothing)

**Comment by bsongis** [comment]
@3djc thanks for testing it! I sent a bin for X-Lite at Nuremberg show with this fix. I will find a better fix now (I hope it won't be another #ifdef)

**Comment by bsongis** [comment]
Perhaps `if (EVT_KEY_MASK(event) == KEY_ENTER) {` ?

**Comment by 3djc** [comment]
Test ok on x7 ;)

**Comment by bsongis** [comment]
Test now ok on xlite as well, thanks!

**Pull request merged**
