### PR TITLE
[ARM] Pulses calculated just in time

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

**Comment by bsongis** [comment]
Well, not sure we are ready for this one ;)

**Comment by projectkk2glider** [comment]
This looked like a very sensible solution. Why did you ditched it?

**Comment by bsongis** [comment]
Nobody tested it! And last problems with B02 radios makes me a little bit more reticent about such changes. Well, this one is not so dangerous, as there is a maximum timeout, I hesitate ...

**Comment by kilrah** [comment]
Need to fix the PXX first anyhow ;)

**Comment by bsongis** [comment]
True!

**Comment by projectkk2glider** [comment]
After looking closely at this code, I think it does not work as intented.

The mixer task is already sleeping when the interrupt sets the time when mixes should be calculated next time. That time won't be used by the mixer thread, because it is already sleeping.

I have another but similar idea, we can use function that sets sleep time of already sleeping task. I will test and prepare this solution.

**Comment by projectkk2glider** [comment]
Final implementation https://github.com/opentx/opentx/commit/29325ad54f12aa373271e77e85afd7157d747b92 is similar, but slightly different. The mixer thread wakes up every tick and checks if it needs to do a mixers calculation. There is no other simple way. The promising CoOS function `CoResetTaskDelayTick()` can not be called from the interrupt.

**Pull request closed without merging**
