### PR TITLE
Aux2: DMA stream incorrect, was not RX but TX

### PR DESCRIPTION
**Pull request by olliw42**
title says it

### CODE REVIEW

**Comment by rotorman** [comment]
Good catch (USART6 RX can only be DMA2 Stream 1 or 2 and Channel 5) and crazy that this has not caused issues earlier:
grafik

**Comment by olliw42** [comment]
it wasn't used with dma by anything so far, I think, only non-dma

**Comment by 3djc** [comment]
Yeap, maybe we should move to dma too, will check when I come back :)

**Comment by olliw42** [comment]
I think for relatively slow and short transitions dma is a bit of overhead
as much as I could see there is no really traffic intense use of the aux2 currently

(I discovered the bug when I started using dma for my mavlink stuff some time back)

btw, as it is currently it also only works for rx, and not tx, if one uses dma, that's because of the nvic is not enabled. I haven't put this into this pr here since aux2 is only used for rx, as much as I can see, so correcting it to work also for tx would be technically a functional change

**Comment by raphaelcoeffic** [comment]
By the way, I found this to be a very useful resource: https://stm32f4-discovery.net/2017/07/stm32-tutorial-efficiently-receive-uart-data-using-dma/

Please note the `DMAFifo` already works like that, however without `HC` or `TC`. Just plain streaming.

**Comment by 3djc** [comment]
This fixes #8677

**Comment by 3djc** [comment]
Thanks

**Pull request merged**
