### PR TITLE
Projectkk2glider/issue 3160 simulator commandline

### LINKED ISSUE #3160: Add commandline options to standalone simulator
* radio type
* eeprom file to use (could also be added to the first dialog box)

### PR DESCRIPTION
**Pull request by projectkk2glider**
…or (radio type and eeprom file)

Help build in :wink: 
```
$ ./simulator21 --help
Usage: simulator [OPTION]... [EEPROM.BIN FILE] 
Options:
 --radio[=]x, -r[=]x  radio to simulate 
 --help, -h           show this help text 

Available radios:
	opentx-9x
	opentx-9x128
	opentx-9xr
	opentx-9xr128
	opentx-9xrpro
	opentx-ar9x
	opentx-gruvin9x
	opentx-mega2560
	opentx-sky9x
	opentx-taranis
	opentx-taranisplus
	opentx-taranisx9e
```

Closes #3160

### CODE REVIEW

**Comment by pointu** [comment]
thanks for the job !
In the futur is there a possibility to specify the model to select ?
I don't know how is organize the .BIN file, and the work it represent ?

**Comment by projectkk2glider** [comment]
That would be more work and would require some changes to pass the model (name) to the simulator itself.

**Comment by pointu** [comment]
i understand well,
At this time the selected model is the first model or the default model ?
And could we specify the directory for the .bin file ?

**Comment by kilrah** [comment]
The model that you selected. It behaves just like the radio, you can change model in the simu or in companion and that one will then be the one that gets loaded...

**Comment by pointu** [comment]
thanks a lot

**Pull request merged**
