### PR TITLE
Horus glider wizard

### PR DESCRIPTION
**Pull request by 3djc**
Introduce basic glider wizard for Horus

### CODE REVIEW

**Comment by kilrah** [comment]
Niiice!

**Comment by 3djc** [comment]
All credits must go to @mhotar for his grafics !

**Comment by bsongis** [comment]
Yes really nice, thanks to you both!

**Review by bsongis — APPROVED** [review]

**Comment by Hjeresen** [comment]
Is it possible to use the glider wizard in 2.2.1?

**Comment by 3djc** [comment]
If you copy the relevant files to your SD wizard directory, then yes

**Comment by Hjeresen** [comment]
Thank you very much i will try it out!

**Pull request merged**
