### PR TITLE
[Horus] Reboot protection reworked to also handle non-WDT events

### PR DESCRIPTION
**Pull request by kilrah**
Please check/comment...

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Why three new variables. Would it not work with just one new variable in `__NOINIT` section?

**Comment by kilrah** [comment]
Well you could by masking, but apart from that I haven't found how to use less than 3 separate storage units and manage to handle all cases and use the "negative logic" we discussed (one case leads to shtdown, every other to staying on). 

A normal boot looks the same as an unrequested shutdown, so we need an additional marker that survives the reset to differentiate the 2. That marker has to always be set straight away to "failure" to be ready for a reboot, so it can't be used to determine the previous reason during use.

Maybe you can find better...

**Comment by projectkk2glider** [comment]
You are probably right. The logic is very complicated. I am afraid we will *forget* why it was done as it is in the future. In fact even now I was not sure why such a complicated setup is needed. Can you put in some additional comments explaining the whole setup.

**Comment by bsongis** [comment]
I will also need a good night before reviewing this one. Please keep it as it is.

**Comment by kilrah** [comment]
As it is:
- We're pretty damn sure to at least keep power on if anything wrong happens
- There is a slight risk we could end up booting normally with warnings instead of in emergency mode, if `shutdownReason` got corrupted. But I'd say that if we can't trust that we probably counldn't trust the watchdog flag used previously either. An additional check for the `unexpectedShutdown` var in storage (read backup ram first, check it, if 1 go to emergency mode, if not reload from SD) but it's likely overkill.

**Comment by projectkk2glider** [comment]
@kilrah @bsongis why was this not merged?

**Comment by bsongis** [comment]
I will try to spend some time on it later during the week-end, too tired now. I am only good for AVR things :)

**Comment by bsongis** [comment]
Travis seems to report an error

**Comment by kilrah** [comment]
Indeed, for the simu... no idea how to fix

**Comment by bsongis** [comment]
Ok I will have a look

**Comment by kilrah** [comment]
I'm being zapped all over the place this morning so I could test in real conditions if this works in case of ESD discharge... and it does, gets into emergency mode as desired. I confirmed the radio just shuts down without it too. 

Interestingly sometimes with a really good fat charge it seems to actually reboot several times until it finally manages to keep running, as suggested by multiple startup audio "pops". 

@projectkk2glider thanks for the simu fix

**Comment by projectkk2glider** [comment]
That is good news, I was worried that the actual power circuit was affected by ESD and that power off was inevitable. Good work :+1:

**Comment by projectkk2glider** [comment]
This fix has been integrated into #4275

**Pull request closed without merging**
