### PR TITLE
GPS datetime display fixes

### PR DESCRIPTION
**Pull request by 3djc**
Fixes glitches I introduced in #5051 

For x7, in telem setup, date and time are alternating, and in telem view, time is displayed in full, but only day-month are displayed

image

### CODE REVIEW

**Comment by bsongis** [comment]
perhaps british will prefer 09-30, no?

**Comment by bsongis** [comment]
@robthomson ?

**Comment by robthomson** [comment]
I will check if this occurs on my setup.  Sofar my telemetry on the X7 with crossfire has been rock solid.

**Comment by bsongis** [comment]
@robthomson just for the date format, the screenshot is above, if it's good for everybody I press the button

**Comment by robthomson** [comment]
Just checked and I dont see these values at all.

I suspect they are being sent by whatever device is plugged into the receiver.

Crossfire rx can receive telemetry from a variety of sources - so my feeling is that this value is likely being sent from an alternative source than the base rx.   (I only use the micro rx)

It would help to know what equipment is plugged into @3djc receiver?

Its entirely possible the issue is not opentx - but the device that is the source for these vars?

**Comment by kilrah** [comment]
This has nothing to do with crossfire, but is about which format to display date in OpenTX... which would for example be coming from a FrSky (or compatible) GPS connected to a receiver.

**Comment by 3djc** [comment]
Ok, back to some consistency :)

x7
image

image


x9
image

image

**Comment by robthomson** [comment]
@kilrah well spotted.. I was muddling up my threads!

But for reference:  DD-MM-YYYY is normal for the UK.

Pretty sure its only USA that use MM-DD-YYYY.

Rob

**Comment by 3djc** [comment]
Yes, but right now, the date setting places use YYYY-MM-DD on the radio, so to keep consistency within opentx, I propsoe for 2.2.1 we fix display as above, and for later on, have a more thourough discusion of date (and well time also) format (since we havereceived one request for AM:PM display)

**Pull request merged**
