### PR TITLE
Companion: Time format for Special Functions Set Timers

### PR DESCRIPTION
**Pull request by davxlw**
otxc_sf_stimer_format

### CODE REVIEW

**Comment by bsongis** [comment]
Nice!

**Comment by bsongis** [comment]
Would you have time to update the release note (and change version number to 2.0.15?)

**Comment by davxlw** [comment]
Ok, will do later.

**Comment by projectkk2glider** [comment]
This should be ported to `next`, right?

**Comment by davxlw** [comment]
If you want, I could do it.

**Comment by bsongis** [comment]
Yes!

**Pull request merged**
