### PR TITLE
#6962 Skin of the `X9D+ 2019` Companion simulator

### PR DESCRIPTION
**Pull request by Ceeb182**
This Pull Request is linked to #6962 issue.

Currently the skin of the `X9D+ 2019` Companion simulator is the same as the one of the `X9D+`. 
I propose a new skin designed for the `X9D+ 2019` simulator.
X9D+ 2019 Image for Companion

To enable screenshot button, it's `bottom_scrnshot` file (usualy it was `left_scrnshot` file). Thank you for telling me if this is a problem.

### CODE REVIEW

**Comment by bsongis** [comment]
Would you use this color?
https://www.youtube.com/watch?v=WhZTXuKV4TI

**Comment by Ceeb182** [comment]
I will try to reproduce the color and texture of this screenshot.
X9D+ 2019 Screenshot

**Comment by Ceeb182** [comment]
What do you think about this version ?

X9D+ 2019 Dark blue

**Comment by bsongis** [comment]
Very nice!

**Comment by Ceeb182** [comment]
I will prepare a new PR this afternoon and I will close this one.

**Comment by kilrah** [comment]
Please just update this one instead of opening/closing all the time.

**Comment by Ceeb182** [comment]
Ok, it's done. I just made a commit on my branch. Is that enough or is there another operation to do?

**Comment by kilrah** [comment]
Nope that's all, you can see it above :)

**Comment by Ceeb182** [comment]
Cool ! :)

**Comment by 3djc** [comment]
I have prepared a PR (https://github.com/opentx/opentx/pull/7054) using this and adding the needed code elements

**Pull request closed without merging**
