### PR TITLE
Fix curves display on colorlcd

### LINKED ISSUE #8040: 2.3.10 TX16S: Active point does not follow curve in Input editor
If an input is specified with two or more lines (e.g. for dual rates), then the graphic is not displayed correctly if the line being displayed is inactive. Both on tx and in Companion.

**To Reproduce**
Download [minimalist setup](https://www.dropbox.com/s/bb6w9oeaejpy9u5/GitHub_CurveBug.otx?dl=0).
Switch SA up to activate first line of input 'Ew'
Open the input editor on the second line ('74%') of input 'Ew'.
Rotate S1

**Expected behavior**
The active point should follow the curve. It does not do so.
Works as expected in OTX 2.3.9.

screenshot_tx16s_20-10-15_17-46-09

screenshot_tx16s_20-10-15_17-27-18

**General information**
 - OpenTX 2.3.10 nightly, initially reported on 2.3.10 stable
 - OpenTX Companion 2.3.10 nightly
 - TX16S

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #8040

### CODE REVIEW

**Comment by PD5DJ** [comment]
Thanks for fixing this :-)

**Comment by Helifunster** [comment]
When will v 2.9.11 will be released?

**Comment by 3djc** [comment]
I guess you mean 2.3.11 ? While we never give eta, it clearly is not very soon. As a reminder, this bug is purely cosmetic, curves actually keep working fine

**Comment by Helifunster** [comment]
Yes, you are right, cosmetic...but really annoying...

Regards


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: 3djc<mailto:notifications@github.com>
Enviado: jueves, 29 de octubre de 2020 12:06 p. m.
Para: opentx/opentx<mailto:opentx@noreply.github.com>
CC: Helifunster<mailto:buzoech1@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [opentx/opentx] Fix curves display on colorlcd (#8057)


I guess you mean 2.3.11 ? While we never give eta, it clearly is not very soon. As a reminder, this bug is purely cosmetic, curves actually keep working fine

**Pull request merged**
