### PR TITLE
Graupner HoTT telemetry update

### PR DESCRIPTION
**Pull request by mha1**
This is an update to the Graupner HoTT telemetry implementation

Content:
- renamed HoTT sensors to allow unambiguous access to sensors provided by different devices (e.g. Vario altitude, GPS altitude) using a naming convention to ensure unique sensor names (see attached file "HoTT sensors.txt")
- added sensor "Revt" to allow access to HoTT warnings issued by HoTT devices (see attached file "HoTT warnings.txt")
- added sensor "Rvpk" to allow access to HoTT VPack (longest time receiver has not seen valid data in [ms]) - PR #8720
- added comments to hott.cpp to clarify data structures and functionality
- fixed issue #8709
- fixed issue #8751
- fixed issue #8759 

Note:
To use the HoTT warnings in sensor "Revt" it is required to update the DIY-Multiprotocol-TX-Module, see accompanying PR https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/pull/627

Attachements:
[HoTT sensors.txt](https://github.com/mha1/opentx/files/7467561/HoTT.sensors.txt)
[HoTT warnings.txt](https://github.com/mha1/opentx/files/7467563/HoTT.warnings.txt)

### CODE REVIEW

**Comment by 3djc** [comment]
Thanks a lot. I take it this encompasses the previous ones

**Comment by mha1** [comment]
Yes it does and thanks for for your time and effort - Michael

**Comment by 3djc** [comment]
Will be available in tomorrow's nightly:)

**Comment by mha1** [comment]
Awesome, but to make full use of this (warnings) we need to wait for Pascal releasing MPM 1.3.3.1

**Comment by mha1** [comment]
I checked the nightly, looks good and works with my private build of the MPM that includes the corresponding extension that will be available in the next MPM release. Thanks again!

**Pull request merged**
