### PR TITLE
[Companion] Smarter app settings import from old versions...

### LINKED ISSUE #4330: Installing Companion 2.2 side by side with 2.1 retains the DFU-Util location
Installing Companion 2.2 side by side with 2.1 retains the 2.1 DFU-Util location in
Settings->Configure Communications...

Presumably it should always update to point to the new install. Like this...?
C:/Program Files (x86)/OpenTX/Companion 2.2/dfu-util.exe

Note: I have Companion 2.0, 2.1, 9X, and 2.2 RC9 installed side by side which I installed in that order over time.  Possibly it was wrong when I installed Companion 2.1 and I fixed the path up.  The current problem may be that the installer is seeing it as user modified and bringing it forward.  There was a similar bug in 2.1 where it retained the 2.0 install path when installed side by side which I worked around by resetting various paths manually.   I'm using Windows 7 Pro SP1

The only reason I can see to retain the existing path is if it is not pointing to the the prior install's location and even then it may be better to reset it to the new install.  I'm not clear why it is user settable so I could be misunderstanding why it should be retained.

Probably not an important bug but I have come across various people using 2.1 that have the DFU-Util location be not set to or possibly set incorrectly which seemed to cause problems for them and this may be the reason.

### PR DESCRIPTION
**Pull request by mpaperno**
Do not import flash tool locations on Windows which are already included with Companion (closes #4330).

Tested, even with companion9x settings which I had in my registry.

The old code had this (what I thought was) strange condition/exclusion:  
`settings21.value(*i) != QString("Start Menu Folder")`  
This sounded more like a setting name (not value) but I couldn't find any instance of either throughout all my old and new Companion settings (5 versions!).  I removed this condition, but maybe someone knows why it was there to begin with?

### CODE REVIEW

**Comment by projectkk2glider** [comment]
See https://github.com/opentx/opentx/commit/08756af9f597d8cd4f26a61544134b049c00cb66 for your question.

**Comment by mpaperno** [comment]
I see... so "Start Menu Folder" was in fact the key name, not value, and the other "blank value" check was supposed to prevent the "(Default)" key (with install path) from being copied.  Did it work?  :-)   I'm not sure because my "Companion 2.2" default key points to the 2.1 install path.  The only place I have a Start Menu Folder is in the OpenTX root key, but I probably chose not to create shortcuts on most installs.

**Comment by projectkk2glider** [comment]
Then the issue #2645 remains. Perhaps @kilrah can chime in. I prefer to stay away from Windows stuff.

**Comment by kilrah** [comment]
Looks good, I'll check when I get a moment

**Comment by mpaperno** [comment]
My earlier "Did it work?" question was rhetorical.  There is no way it could have worked, for a number of reasons.  I've tested this new code with a variety of situations and old Companion versions.  It is fundamentally same as old version, just less code duplication (plus the fixed issues).

The "better" way to do this import would be to have a list of all setting key names currently being used and only import those (or migrate values from old key names as needed).  But with the current architecture this would require yet a 3rd place where the key names are defined.  I'd rather refactor the system so the key names and default values are only specified once, but this would take more time and testing, and probably not a high priority right now.

**Pull request merged**
