### PR TITLE
Companion/Sim: Add more fields to telemetry simulator UI

### PR DESCRIPTION
**Pull request by mpaperno**
Hello, is this the right place/branch for this?  I don't really use the "next" branch.  LMK if there's a better way.

Anyway, this just adds a bunch more telemetry values that can be sent to the simulator (F4 feature in Sim GUI).  Can use hex notation for values, and blanks are now skipped instead of sending zero value.

Cheers, 
-Max

simu-values

### CODE REVIEW

**Comment by kilrah** [comment]
Seems good, thanks!
But before I merge could you please just fix indents to our standard? No tabs, 2 spaces per indent.

**Comment by mpaperno** [comment]
My bad, fixed.

**Comment by kilrah** [comment]
Thanks, merged for 2.0.16. If you want it to also be in the upcoming 2.1 version you should also create a similar pull request based on the next branch.

**Comment by projectkk2glider** [comment]
@mpaperno nice :+1:

**Comment by Awapp** [comment]
Very nice. Is it possible to add "Cell" since this is my major alarm.

**Comment by mpaperno** [comment]
I believe that the value for "cell" (the cell with the lowest voltage) is derived from the "CELLS" telemetry value(s) received.

-Max

**Comment by kilrah** [comment]
Correct. The simulator expects a 32-bit value containing all cells according to the telemetry protocol, and the firmware then calculates Cell and Cells form those values.

**Pull request merged**
