### PR TITLE
[sim] Cosmetics for switch position macros

### PR DESCRIPTION
**Pull request by mpaperno**
Also removes PCBFLAMENCO from simuSetSwitch -- @bsongis Is this OK?  There are only a few other mentions of PCBFLAMENCO in this file... maybe they can all be removed?

### CODE REVIEW

**Comment by 3djc** [comment]
I was planning to remove all references to it in a single pr once thing are more quiet, so we can get it back should it be needed

**Comment by mpaperno** [comment]
I put "PCBFLAMENCO" in the commit notes so it could be searched, but I could put the code back. It was commented out anyway though... seemed extra useless.

**Comment by 3djc** [comment]
No no I was just doing heads up don’t spend time chasing those, I will , but your pr should not be changed because of that

**Comment by mpaperno** [comment]
👍

**Comment by bsongis** [comment]
needs some merge work

**Comment by mpaperno** [comment]
Rebased.

**Comment by bsongis** [comment]
Thanks!

**Pull request merged**
