### PR TITLE
Splash screen cleanup, new splash_dmg.png added

### PR DESCRIPTION
**Pull request by mhotar**
Please check this pull request carefully. I really do not know if this is correct way to replace this file :)
splash_dmg

### CODE REVIEW

**Comment by bsongis** [comment]
Someone with a OSX ?

**Comment by raphaelcoeffic** [comment]
We probably need to adjust some properties a bit:

Screen Shot 2019-09-03 at 07 32 22

**Comment by raphaelcoeffic** [comment]
Now it should be ok

**Comment by raphaelcoeffic** [comment]
This is how it looks like now:
Screen Shot 2019-09-03 at 07 58 19

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
@mhotar thx a lot! It's really looking nice!

**Pull request merged**
