### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by LapinFou**
Here are the latest translations.
One question, what is `Act` ??

### CODE REVIEW

**Comment by kilrah** [comment]
Activity. Goes false after backlight timeout

**Comment by LapinFou** [comment]
Oh ! OK.
So,
Act is TRUE when the backlight is ON
Act is FALSE when the backlight is OFF

Correct ?

**Comment by kilrah** [comment]
Yes

**Comment by LapinFou** [comment]
Thanks for the clarification.
👍

**Pull request merged**
