### PR TITLE
#3507: raise max RPM in telemetry simulator to 262143 (0x3FFFF)

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Closes #3507

**Comment by projectkk2glider** [comment]
@raphaelcoeffic I would be better to integrate this into the #3506 because both pulls affect the same parts of the code and merging them will likely produce conflicts.

**Comment by raphaelcoeffic** [comment]
@projectkk2glider Ok, no problem, I'll do it together with the other comments as soon as I get a minute or two. Thx for reviewing!

**Comment by raphaelcoeffic** [comment]
Changes integrated into pull request #3506

**Pull request closed without merging**
