### PR TITLE
#1471 - libio added to Lua. For tests, can be simplified and expanded

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

**Comment by bsongis** [comment]
```lua
local function run(event)
  local f = io.open("/opentx.h")
  local str = io.read(f, 10)
  print(str)
  io.close(f)
  return 1
end

return { run=run }
'''

**Comment by bsongis** [comment]
also io.write is implemented

**Comment by bsongis** [comment]
and io.close

**Comment by bsongis** [comment]
If it works it's easy to add the seek, I will add it if nobody else does it before

**Comment by kilrah** [comment]
Hmm, with that script I just get a brief flash of the screen.

Changed it to:

```lua
local function run(event)
  local f = io.open("test.txt")
  local str = io.read(f, 10)
  lcd.clear()
  print(str)
  io.close(f)
  return 0
end

return { run=run }

The test.txt file (with a "hello world!" inside) seems to be found as I get a syntax error if not present, but I just get a blank screen.

**Comment by bsongis** [comment]
Yes, this print was for simu (it only writes text on the console!). Would you try with lcd.drawText(...) ?

**Comment by kilrah** [comment]
Hmm the "a" still seems to do the same as "w"

**Comment by bsongis** [comment]
The "a" should first go to the end of file

**Pull request merged**
