### PR TITLE
fix for issue 2758 lua support for latitude and longitude

### PR DESCRIPTION
**Pull request by dsbeach**
This provides lua access to latitude and longitude in decimal degree format.

Snippet of lua code demonstrating usage"
```lua
local function init()
  gpsId = getTelemetryId("GPS")
end

local function background()
  gpsLatLon = getValue(gpsId)
  if (type(gpsLatLon) == "table") then
   -- fields gpsLatLon["Lat"] and gpsLatLon["Lon"] contain valid position data in decimal degrees
  end
end
```
Code has been tested in companion21 and on Taranis hardware using both FrSky and Altis GPS hardware.

### CODE REVIEW

**Comment by bsongis** [comment]
It seems ok to me. Anybody else?

**Comment by dsbeach** [comment]
I'm comfortable with the changes and think it is good to go.  The next question is how / where to provide documentation regarding migrating 2.0.x lua scripts to 2.1.x.

My next hurdle in converting my sailplane GPS racing script is it's use of lcd.lock().  It appears that telemetry scripts will no longer be able to process PLUS and MINUS keypresses, or am I missing something?

David

**Comment by projectkk2glider** [comment]
>My next hurdle in converting my sailplane GPS racing script is it's use of lcd.lock(). It appears that telemetry scripts will no longer be able to process PLUS and MINUS keypresses, or am I missing something?

See #2469.

> The next question is how / where to provide documentation regarding migrating 2.0.x lua scripts to 2.1.x.

Good question. Bertrand started something on https://github.com/opentx/lua-reference-guide

**Comment by projectkk2glider** [comment]
Tested in simulator with the help of gdb. Everything OK.

**Comment by projectkk2glider** [comment]
Thanks!

**Comment by wolkstein** [comment]
hi,
i try this under opentx 2.1.3. as i am right it is inside this release, or?
no success, even GPS is receiving data from telemetry and is also displayed in taranis model setup telemetry tab as Sensor GPS ID is 0800. and i can see my current coordinates there.

i try it like this:
``` lua
           -- in init
          local gpsLatLon = {}
          local LocationLat = 0
          local LocationLon = 0

           -- in run function
           gpsLatLon = getValue(getTelemetryId("GPS"))
          if (type(gpsLatLon) == "table") then
                LocationLat = gpsLatLon["Lat"]
                LocationLon = gpsLatLon["Lon"]
          end
```
what did i do wrong?
thx.

/g
wolke

**Comment by projectkk2glider** [comment]
The names of table fielsd were subsequently changed to lower case in 8b8391101779d85c48e2709c560f8ee78f65111e

Use `lat` instead of `Lat` and `lon` instead of `Lon`:
```lua
           gpsLatLon = getValue("GPS")
          if (type(gpsLatLon) == "table") then
                LocationLat = gpsLatLon["lat"]
                LocationLon = gpsLatLon["lon"]
          end```

**Comment by wolkstein** [comment]
Thx,
now it works here(opentx2.1.3) like a charmer:).
/g
wolke

**Pull request merged**
