### PR TITLE
Horus: add receiver number check

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Basically checks whether or not a receiver number is already used. In case it is, a warning is displayed.

Cases covered:
- check RX ID on any relevant change in module/proto/ID.
- assign a new free receiver ID on new model (internal RF).
- find the next free receiver ID while editing it (long press ENTER while editing).

The same features are now available as well on std LCD.

### CODE REVIEW

**Comment by bsongis** [comment]
Not related, what about changing this cli to a binary protocol + a python cmdloop script?

**Comment by raphaelcoeffic** [comment]
@bsongis I like it to be able to connect just with a plain serial Terminal, without anything further. Do you have any special plans for the CLI?

**Comment by bsongis** [comment]
Yes, I would like to see history, completion and more features without spending more flash, the python cmdloop script would connect to the serial port, send / receive binary data etc.

In short the same way adb works ...

**Comment by raphaelcoeffic** [comment]
@bsongis I just rebased on top of 2.2, to avoid conflicts.

**Comment by bsongis** [comment]
rebase needed :(

**Comment by raphaelcoeffic** [comment]
@bsongis done, rebased on top of new `2.2`

**Pull request merged**
