### PR TITLE
Companion fix sources lists for X10 and T16 radios and improve radio conversion of sources

### LINKED ISSUE #7879: Companion : ??? in sources instead of EX1/EX2
2.3.9 and current nightlies

image

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #7879 and #7593
Improve sources conversions between radios eg #7624

### CODE REVIEW

**Comment by elecpower** [comment]
X9D X10 X12S

**Comment by elecpower** [comment]
The first screen shot is from X12S profile and the second is the conversion errors when opening the file using X10 profile. LS and RS should convert.
Screenshot from 2020-08-20 07-58-12
Screenshot from 2020-08-20 07-57-29

**Comment by elecpower** [comment]
Converting X10 to X12S
Screenshot from 2020-08-20 08-22-50
Screenshot from 2020-08-20 08-11-11
Screenshot from 2020-08-20 08-12-42

**Comment by bsongis** [comment]
Thanks!

**Comment by robustini** [comment]
Thanks!

**Pull request merged**
