### PR TITLE
Michele villa/C9x italian translation

### PR DESCRIPTION
**Pull request by MicheleVilla**

### CODE REVIEW

**Comment by bsongis** [comment]
Would you do a git rebase origin/next to avoid all those merge?

**Comment by MicheleVilla** [comment]
this was only an upgrade for master section before the 2.0.14 release
May you explain to me the right way?
(As you understand I'm not very clever...)

**Comment by bsongis** [comment]
I tried different things but it doesn't work. I don't understand if you are trying to change translation into 'master' or 'next'. In your place I would open a new branch from scratch, copy the files which you changed inside and reopen a pull request!

**Comment by projectkk2glider** [comment]
@MicheleVilla just create a new pull from the same branch, but this time first choose `master` as the **base** before you click on button `create pull request`.

**Pull request closed without merging**
