### PR TITLE
Avoid Bluetooth fifo full (and 1ms wait in the mixer task...)

### LINKED ISSUE #7375: Rescue Mode Horus X12S Bluetooth telemetry OTX 2.3.5
On openTX 2.3.5 in Horus X12S when the telemtetry of the Crossfire is redirect to the internal Bluetooth, the radio reboot in Rescue Mode.

### PR DESCRIPTION
**Pull request by bsongis**
Should fix #7375

### CODE REVIEW

**Comment by Bendau** [comment]
Thank you very much for the work ! If i want to test, is it intergate in the 2.3.8N225 ?

**Comment by bsongis** [comment]
Yes of course!

**Comment by bsongis** [comment]
we will be glad to get a feedback from you on this

**Comment by Bendau** [comment]
I just wanted to thank you very much! It works !!! I think I can at least contribute by making a small gesture via Paypal ;)

**Comment by brainbubblersbest** [comment]
No s. Port out with bound hm-10 or hm-18
On 2.3.2 that has worked for sure.
Bt led Red Shows connection, Green blinking led has shown data transmission. With 2.3.7 this Green led is permanent dead. Need S. Port over bt for tracking.
#7631

**Pull request merged**
