### PR TITLE
WIDGET: Timer2

### PR DESCRIPTION
**Pull request by offer-shmuely**
Timer2 Widget 
A Timer version with bigger font for easier reading, that fill better the screen real estate

suggested: as adding to the existing one (side by side)

### CODE REVIEW

**Comment by offer-shmuely** [comment]
Widget view on 1/8 size

1_timer-vs-timer2

Widget view on 1/4 size

2_timer-vs-timer2

**Review by 3djc — COMMENTED** [review]
There is no reason for Battcheck to be included in this PR, is there ?

**Comment by offer-shmuely** [comment]
No, there is no reason, that a technical mistake, will try to see how to fix it.

**Comment by offer-shmuely** [comment]
I don't know how to fix it.
I will close this pull request, and open a clean one

**Pull request closed without merging**
