### PR TITLE
[companion][logsdialog]Backport fix for #2163 from next to master.

### PR DESCRIPTION
**Pull request by griebd**
Improve performance of graphs plotting on master, same code from next. (QCustomPlot updated as well)

### CODE REVIEW

**Comment by projectkk2glider** [comment]
This code is extremelly fast! Good work @griebd 

But I noticed a bug, using large log file http://wikisend.com/download/803076/ShadowF5X-2015-04-12.csv containing three sessions:
* when the whole file is displayed, all is OK
* first session is displayed OK
* second session has wrong time stamps in the first part, then has a blank range somewhere in the middle, something is wrong here.

**Comment by projectkk2glider** [comment]
screenshot

Example of above bug: 
* the part with the constant altitude from about 10:32:00 is wrong
* the time at beginning should be 10:37:53

**Comment by griebd** [comment]
Thanks @projectkk2glider! The problem was that the X axis values weren't selected "from the selection" in fly sessions.

**Comment by projectkk2glider** [comment]
All good now, merging. Thanks!

**Pull request merged**
