### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by LapinFou**
Updated French translations.

### CODE REVIEW

**Comment by bsongis** [comment]
Almost impossible to review :(

**Comment by LapinFou** [comment]
Why ??

**Comment by LapinFou** [comment]
I did exactly how you explained me last time, one commit after updating the ``ts`` file, then a 2nd commit with the translations itself.
The commit https://github.com/opentx/opentx/pull/5045/commits/c9ae4661d6b99d74f7ba13e76137943d78173d7e looks OK to me for review.

**Comment by bsongis** [comment]
I went too fast and didn't see the 2 commits, sorry for this!

**Comment by LapinFou** [comment]
C'est vrai quoi !! Le disciple respecte à la lettre les consignes du grand Maître vénéré, mais il se fait taper dessus... Pfffff c'est vraiment trop injuste... Ou est-ce que j'ai mis ma coquille déjà ?!? 😥 

😁 😆 😉

**Comment by bsongis** [comment]
:)

**Pull request merged**
