### PR TITLE
What about this?

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

**Comment by bsongis** [comment]
I hope I didn't break everything with boyscout work ;)

**Comment by romoloman** [comment]
Andrè: looking to the sort of comments I received on other branches, I see we are looking for perfection here. So I would also like a UI perfection and not only a code one :)

**Comment by bsongis** [comment]
Agree about perfection on both sides :)

**Comment by kilrah** [comment]
Yep. We had 2 branches, one with good code and one with good looks, as people don't always master both we just need to merge everything together ;)

**Comment by bsongis** [comment]
@romoloman Thanks it's really nice now. Even one POT now renders fine, the pot is centered!

**Pull request merged**
