### PR TITLE
update function is required

### PR DESCRIPTION
**Pull request by 3djc**
If not, it gnerates lua errors when not displayed. it can be empty, but since we have one, let's keep it counting !

Thx Noircogi for spotting this one

### CODE REVIEW

**Comment by bsongis** [comment]
I like this change, but the background function should be optional (as it is in telemetry scripts). I guess I missed something, what is the error?

**Comment by 3djc** [comment]
The error is that background gets called no matter what in interface.cpp and genrate an error in LuaWidget::background(). We could of course check for presence of the background prior trying to execute it

**Comment by bsongis** [comment]
Yes I think it is done this way in telemetry scripts

**Comment by bsongis** [comment]
And I did it for function scripts recently. I forgot widgets scripts for sure

**Pull request merged**
