### PR TITLE
Multi improvements

### PR DESCRIPTION
**Pull request by schwabe**
- Syncing multi output with rf output
- Implement configuration of multi from OpenTX (inverted or not)
- implement Failsafe settings for Multi (AFHDS2A only for now)

### CODE REVIEW

**Comment by elecpower** [comment]
@schwabe I think this may have broken Companion running on Ubuntu 16.04. After a fresh local compile with all the latest merges I get the following from the command line launch.
neil@otx22:/opentx/build-taranis-debug$ ./companion22
ASSERT: "rd.maxSubtype + 1 == (unsigned int) rd.protocols.length()" in file /home/neil/opentx/companion/src/multiprotocols.h, line 64
Aborted (core dumped)
neil@otx22:/opentx/build-taranis-debug$

**Comment by 3djc** [comment]
Whats you cmake line ?

**Comment by schwabe** [comment]
@elecpower I pushed a fix for that, although I wonder why Q_ASSERT does not do anything for me...

**Comment by elecpower** [comment]
cmake -DPCB=X9D+ -DGVARS=YES -DLUA=YES -DHELI=NO -DDEBUG=YES -DALLOW_NIGHTLY_BUILDS=YES -DUSB=MASSSTORAGE -DCMAKE_BUILD_TYPE=Debug ../

**Comment by elecpower** [comment]
@schwabe Just a guess but is line 88 of multiprotocols.cpp the problem?
  {MM_RF_CUSTOM_SELECTED,  **7**, true,       **NO_SUBTYPE**,          STR_MULTI_OPTION},

**Comment by schwabe** [comment]
@elecpower yes, I think you overlooked the "I pushed a fix for that" (084680b5fd24a50a9e798a75073b8bf3feb00848)

**Comment by elecpower** [comment]
@schwabe sorry didn't realised you pushed a fix just now

**Comment by 3djc** [comment]
Just tested the fix, seems ok here

**Comment by elecpower** [comment]
Tested okay

**Comment by mpaperno** [comment]
> I wonder why Q_ASSERT does not do anything for me...

Q_ASSERT is only active in Qt debug builds (which occurs by default with `CMAKE_BUILD_TYPE=Debug`) or if specifically forced.  From qglobal.h:

```c++
#if !defined(Q_ASSERT)
#  if defined(QT_NO_DEBUG) && !defined(QT_FORCE_ASSERTS)
#    define Q_ASSERT(cond) do { } while ((false) && (cond))
#  else
#    define Q_ASSERT(cond) ((!(cond)) ? qt_assert(#cond,__FILE__,__LINE__) : qt_noop())
#  endif
#endif
```

**Pull request merged**
