### PR TITLE
[Companion] Implement print functions for the hell setup screen (fixe…

### LINKED ISSUE #3430: Missing Heli screen from print and compare models in Companion
The print and compare models options on the Companion are both missing any information from the Heli screen of the Editing window.

### PR DESCRIPTION
**Pull request by schwabe**
…s #3430)

*edit (added by projectkk2glider):* Closes #3430

### CODE REVIEW

**Comment by schwabe** [comment]
Screenshot:
image

**Comment by projectkk2glider** [comment]
Looks good, I will test and merge it later today.

**Comment by projectkk2glider** [comment]
One problem: `Long. cyc` and `Lateral cyc` values are swapped in printout.

One idea: Display heli settings only when any value (weights and swash type) is different from the defalult (0).

**Comment by schwabe** [comment]
@projectkk2glider I updated the commit and show the heli now only if the swash type is something else than off

**Comment by projectkk2glider** [comment]
Perfect, thanks!

**Pull request merged**
