### PR TITLE
Re #4224: Enable reading and writing Models and Settings from/to Horu…

### PR DESCRIPTION
**Pull request by projectkk2glider**
…s radio (SD card)

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Filename/window title for mdichild is kind of wrong. It should be `<something>.otx`. Not sure where to fix this.

**Comment by kilrah** [comment]
Opening from radio, then clicking File->Save saves straight on radio. It should rather prompt to save to .otx somewhere to keep homogeneity, only write to radio with "write models and settings"

**Comment by projectkk2glider** [comment]
>Opening from radio, then clicking File->Save saves straight on radio. It should rather prompt to save to .otx somewhere to keep homogeneity, only write to radio with "write models and settings"

Yes, and the cause for this is the same as:

>Filename/window title for mdichild is kind of wrong. It should be <something>.otx. Not sure where to fix this.

**Comment by bsongis** [comment]
Thanks! I will try to take care of the .otx problem

**Pull request merged**
