### PR TITLE
MAVLINK Adaptation for SKY9X and 9xRPRO

### PR DESCRIPTION
**Pull request by adriano65**
Hi,
my name is Adriano and i modified v2.13 to
compile for sky9x with MAVLINK protocol.
It is working and i kindly ask you can include
these very little mods in mainstream.

Thank you for all your great job

note: i use slackware-linux(64bit) and gcc 4.7.3 and it compiles OK :-)

### CODE REVIEW

**Comment by bsongis** [comment]
@adriano65 We have a compilation error on 9XR with MAVLINK extension, would you please have a look?

telemetry/mavlink.cpp:76:25: error: 'MAVLINK_rxhandler' was not declared in this scope
make: *** [opentx.elf] Error 1

**Comment by adriano65** [comment]
I am happy to correct that bug.
Since i am in a middle of my fork modifications,
i think to get your "master" version, correct, and submit a pull request...
Am i right ?

**Comment by bsongis** [comment]
Yes, thanks a lot!

**Comment by rubenverhoef** [comment]
Hello, is the mavlink protocol working for the 9XR PRO ?

**Comment by adriano65** [comment]
Hi Ruben,
I am sorry, but it is 5 month i don't work on mavlink, I think i'll restart after August.
From what i remember, tho opentx/master should work on 9XRpro
Alternatively you can check my fork and give a try..
Bye

**Comment by rubenverhoef** [comment]
I don't have the 9xr Pro because i think the mavlink telemetry is not working. I will buy the 9xr (normal) but it is out of stock. I'm looking for the 9XR 2nd hand.
I want to use the OrangeRX with mavlink Telemetry. This: http://www.rcgroups.com/forums/showthread.php?t=1913501

I will buy the 9XR Pro when the 9XR Pro is working with OrangeRX and Mavlink.

**Pull request closed without merging**
