### PR TITLE
Bsongis/issue 2183 failsafe settings on individual channels

### PR DESCRIPTION
**Pull request by bsongis**
For review. The companion part is needed. I will squash all commits into one at the end

### CODE REVIEW

**Comment by bsongis** [comment]
It's not so nice, I will rely on @mhotar for a nice idea :)

**Comment by bsongis** [comment]
[Enter] switch to edition mode
then setup the value with the stick / mix / etc.
[Enter] save the value
or [Exit] back to the previous value

When not in edition mode:
[Enter Long] Hold
[Enter Long] No pulses
[Enter Long] back to the channel value
in a loop ...

**Comment by kilrah** [comment]
Tested and working!

**Comment by mhotar** [comment]
@bsongis, Nice job as usual !
I would only center these texts if possible.
snapshot_06
Please also consider to add manual setup mode using UP and DOWN buttons directly instead of channel value. Simply when you enter the edit mode, values will be taken from the channel, when you press UP or DOWN (in edit mode active), values will be changeable only by these buttons and the CHxx will change to [see the picture]

**Comment by kilrah** [comment]
I don't like the dots, too heavy ;) Not sure about manual edit, is that really useful?

**Comment by projectkk2glider** [comment]
I've glanced over the code changes. Nothing bad spotted.

**Comment by bsongis** [comment]
@mhotar Then I propose [Enter Long] in edit mode takes the channel value, while otherwise [Up] and [Down] allow the user to manually modify the value.

**Comment by kilrah** [comment]
Yes I prefer that too!

**Comment by bsongis** [comment]
Here it is, comments welcome!

**Comment by kilrah** [comment]
Great! :+1:

**Comment by mhotar** [comment]
Yes, clever and nice!

**Comment by bsongis** [comment]
Ok I will squash everything in one commit tomorrow and let you merge into 'next'

**Pull request merged**
