### PR TITLE
Companion update model references from enhanced context menus

### PR DESCRIPTION
**Pull request by elecpower**
Based on feedback on #7025

In summary:
- new function to search and replace object references across the current model;
- new class for adjustment references;
- new and amended functions to support this change and for future refactoring across Companion;
~~- initially trigger from enhanced logical switches context menu (others if this PR accepted);~~
- housekeeping.

Notes:
- tested across all object types though still testing all use cases;
- some more debug and timing code needs to be removed;
- surprisingly the update executes fast, screen fresh is the slow part;
- tried to future proof eg shift action for values other than +/- 1;
- without lua plumbed into Companion placeholders for updates in scripts;
- once again highlights the need to centralise refreshing combo box lists (maybe my next challenge).

### CODE REVIEW

**Comment by elecpower** [comment]
Enhanced menus and added updating references to:
- Logical Switches
- Channels
- Curves
- Flight Modes
- Global Variables

Reworked update references to better work with enhanced menus.

**Comment by elecpower** [comment]
Enhanced menu and added updating references to Inputs
Rebased and fixed conflict with #7415

**Comment by 3djc** [comment]
Oops sorry if we clashed with your pr with #7415. Let us know when you want us to review, since you have set incomplete flag (no rush !)

**Comment by elecpower** [comment]
@3djc not a problem with the clash. It has just taken me so long to develop the PR as it is a monster. PS I was considering adding T5 & T6 too but you beat me.
The model edit plumbing for the PR is ~~now~~ nearly complete (missed Timers). Next task is Timers context menu and then to create complex models to test the update references code. I am hoping just another week or two and then release for review.

**Comment by elecpower** [comment]
Enhanced menu and added updating references to Setup Timers.
Back to testing

**Comment by elecpower** [comment]
Cascading updates added

**Comment by elecpower** [comment]
Fixes #7470

**Comment by elecpower** [comment]
So after extensive but not exhaustive testing this PR is ready for review.
I had to create unrealistic models to test the multitude of combinations so using a wide range of real models should provide a better series of tests scenarios.
Includes some housekeeping where minor changes.
Increased the amount of model edit refreshes but there are more needed and likely there needs to be a refactor to standardise the code to make this easier.
If you would like me to rebase and squash the commits so you can test in your local repos without merging into 2.3 just let me know.

**Comment by bsongis** [comment]
Thanks!

**Pull request merged**
