### PR TITLE
Port Wizard to X7

### PR DESCRIPTION
**Pull request by schwabe**
Wizard ported to X7. Markus did all the work. I am just making the pull request since he is not familar with git.

### CODE REVIEW

**Comment by schwabe** [comment]
image
image
image

**Comment by 3djc** [comment]
Thanks for helping Markus. I tried the scripts, and there are display glitches in quite a few places. It probably needs more display work to cope with the small space available on x7

**Comment by MarkJohann** [comment]
Hello 3djc I worked on it in the evening
and there is now a version 3 of the wizard. The display views are already a lot better.
Thank you for your feedback. and I think version 3 is now better from the display views.
Yes the Display is very Small :-)

**Comment by 3djc** [comment]
Happy to test that when they are uploaded, will free some time to help too ! Tschuss, 3djc !

**Comment by MarkJohann** [comment]
Because I do not know how to put something here online. I put the new version in a Fourm online. if you tell me how I send you the version or how I can put it here online. I would be very happy if you can test the new version and give me feedback what should be changed
Thank you for your help

**Comment by squarecode** [comment]
It looks like #5198 is already one step ahead... I personaly prefere his design choice on the small screen oft the X7. The screen glitch visible in the Video and Simulator has been fixed at least for me.

**Comment by MarkJohann** [comment]
I have now done a redesign. And as far as everything fits in the small Dispaly. Since I want to widen the wizard by other functions.
I leave the design the way it is. Since it works and it is now more important to extend the functions. in the field of glider you can improve a lot and the area Helicopter should also find its way into the Wizard. these are my next steps. In the evening I will present the next version online with a few changes ..

**Comment by 3djc** [comment]
Since we merged another x7 wizard with similar features, I'm going to close this, but not before thanking you for the work done, which did help move Otx x7 forward ! Danke schön !

**Comment by driver33** [comment]
05.09.2017 2:45 PM "Arne Schwabe" <notifications@github.com> napisał(a):

**Pull request closed without merging**
