### PR TITLE
Mixers monitor

### LINKED ISSUE #1945: [OpenTX] [Companion] [enhancement] MIXERS MONITOR
In the mind of #1399, it could be handy to have MIXERS MONITOR to see clearly what's going on, without being distracted by the servos settings:

channel_monitor
                          **short [ENT]**
mixers_monitor

It could be accessed from the CHANNEL MONITOR (by the way, CHANNELS or maybe SERVOS would be more appropriate) with a short [ENT] press, and remember it's last state (channels or mixers).

### PR DESCRIPTION
**Pull request by davxlw**
Fixes  #1945.

In the CHANNELS MONITOR view, pressing [ENT] would alternate between channels and mixers view.

The build option from  #1399 could be removed.

### CODE REVIEW

**Comment by davxlw** [comment]
I understand that this new screen could confuse people...
However, I would prefer not to have to keep track of my branch every time the code evolves.
So, I suggest to replace the "CHANNELS_MONITOR_INV_HIDE" buid option by "MIXERS_MONITOR", I will try to do it myself if you wish.

**Comment by bsongis** [comment]
Exactly with a Makefile option everybody will be happy. Careful, won't you break things for those who use this CHANNELS_MONITOR_INV_HIDE option and don't need this new screen? Or perhaps you are the only one using this option? I can't remember who added it, not me for sure.

**Comment by davxlw** [comment]
As you can see above with #1399, I was the original applicant and yes, probably the only one using that.
I don't see any problem in replacing this option, as the mixers monitor provides this functionality without changing the normal behavior of the channels monitor. It's only better IMHO.

At worst, I would just have to add it again :wink:

**Comment by MicheleVilla** [comment]
Is possible to add this option in "Companion compilations options"?
it is possible that someone else might appreciate this option

**Comment by davxlw** [comment]
Ok, sorry for the mess with the commits...

When we'll agree with what to do, I'll close this pull request and make a new one.

**Comment by bsongis** [comment]
Yes it is possible to add another option on the compilation server.

**Comment by MicheleVilla** [comment]
With option "Change view  from Mixer monitor  to Channel monitor" by ENT Key

**Comment by davxlw** [comment]
I've replaced "CHANNELS_MONITOR_INV_HIDE" with "MIXERS_MONITOR" and added that to Companion firmware build options as "mixersmon".

 It should work but it needs to be reviewed ;)

**Comment by davxlw** [comment]
No comments ?

**Comment by bsongis** [comment]
I still didn't read it, I will do, I promised the BT driver to FrSky first

**Comment by davxlw** [comment]
No problem.

**Comment by bsongis** [comment]
Would you remove the unneeded files from the review?

**Comment by davxlw** [comment]
Do you talk about the .ts files ?
If so, I've planned to remove them.

**Comment by projectkk2glider** [comment]
I think you should just change the line endings on files that contain huge amount of changes like companion/src/translations/companion_it.ts

**Comment by davxlw** [comment]
I have already removed the .ts files...

But now that you're talking about line endings, I think the repo is a little messy in that respect, there's some inconsistency between windows and linux type. I'm on linux so it shouldn't be a problem.

**Comment by bsongis** [comment]
Right the line endings will be fixed, but not now or all pull requests will be invalid! Once done I will add a check-lines-ends job to jenkins at each commit.

**Comment by bsongis** [comment]
Would you add the same feature to the 'next' branch?

**Comment by davxlw** [comment]
Ok, will do it this week end.

**Pull request merged**
