### PR TITLE
sdio_sd.c fixes from another project I found on the web - not tested

### PR DESCRIPTION
**Pull request by bsongis**
Still not tested

### CODE REVIEW

**Comment by projectkk2glider** [comment]
Looks reasonable, I will test it later.

**Comment by bsongis** [comment]
Source 1: 
https://github.com/RT-Thread/realboard-stm32f4/blob/master/software/examples/drivers/sdio_sd.c

**Comment by bsongis** [comment]
Source 2:
https://my.st.com/public/STe2ecommunities/mcu/Lists/cortex_mx_stm32/DispForm.aspx?ID=43376&Source=/public/STe2ecommunities/mcu/Tags.aspx?tags=2

**Comment by bsongis** [comment]
The Source 2 seems to say that my port is not good and the right version is the previous one. I don't see why.

**Comment by bsongis** [comment]
Source 3 seems also saying my fix is bad:
https://my.st.com/public/STe2ecommunities/mcu/Lists/cortex_mx_stm32/Flat.aspx?RootFolder=https%3a%2f%2fmy%2est%2ecom%2fpublic%2fSTe2ecommunities%2fmcu%2fLists%2fcortex_mx_stm32%2fTiming%2c%20DMA%20%20SDIO%20Bug%20in%20Standards%20Peripherals%20Examples%20V3%2e5%2e0&FolderCTID=0x01200200770978C69A1141439FE559EB459D7580009C4E14902C3CDE46A77F0FFD06506F5B&currentviews=1930

**Comment by projectkk2glider** [comment]
Manual says:
```
SSDIO/DMA interface - procedure for data transfers between the SDIO and
memory:
1. Do the card identification process
2. Increase the SDIO_CK frequency
3. Select the card by sending CMD7
4. Configure the DMA2 as follows ...
5. Send CMD24 (WRITE_BLOCK) as follows ...
```

**Comment by bsongis** [comment]
Agreed, this PR is completely wrong

**Pull request closed without merging**
