### PR TITLE
TX16S : mirror FrSky telem at 57k

### PR DESCRIPTION
**Pull request by 3djc**
Looking for feedbacks, for 57k seems more logical for AUX FrSky telemetry mirror

### CODE REVIEW

**Comment by brainbubblersbest** [comment]
Whooops. A lot of users in the AAT Community already use that connection with 115200baud.

Because a long time OTX dont supported AUX baudrate changes, the Tracker Projects changed their used Baud speeds instead. 

This commit would cause i compatibility again and straight away. 

A lot better would be a Baudrate setting by Users Choice.

A Big Enhancement would be to  change the Baudrate on both Aux Serials in General for enhanced Pheriphal compatibility. 57600/115200/450000
#8685 

Please @3djc !

This would be Nice for Users of that Connection
And of Course for the Mav Link Branch in combination with different Telemetry Radio Types.

**Comment by 3djc** [comment]
Choice is unfortunatly not an option before 2.4 as we are out of eeprom space

**Comment by brainbubblersbest** [comment]
Thank you for that acceptable argument.
As another option:
Maybe that commit can wait then till 2.4?
I Just expect alot of Users struggling again, 
with setup their Hardware again over AT Commands.
and Custom Compiled Tracker FWs and/or Applications after the next OpenTX Update.
I just wanna mention my Thoughts. 
After all its the Decission from you Devs.

**Comment by 3djc** [comment]
Changing it now would probably create more issues than it solves, so will be done when we can introduce speed choices

**Pull request closed without merging**
