### PR TITLE
Add varioCenterSilent option to x7 and rework telem screen accordingly

### LINKED ISSUE #4921: Q-X7 with 2.2 Vario silent check box
My buddy has just bought an X7, we installed the latest OTX 2.2
On the telemetry page, the "Silent/Tone" check box seems to be missing??

### PR DESCRIPTION
**Pull request by 3djc**
image
This fixes #4921

### CODE REVIEW

**Comment by kilrah** [comment]
Why was that closed again?

**Comment by mpaperno** [comment]
All the pending PRs got closed when branch was renamed.  :-/

**Comment by kilrah** [comment]
This should fix it?

**Comment by mpaperno** [comment]
Cool!  I didn't see a way to edit the base branch before, but now I found it.

**Comment by kilrah** [comment]
not sure which other PRs need reopening...

**Pull request merged**
