### PR TITLE
Add Jumper t12 support

### PR DESCRIPTION
**Pull request by 3djc**
- Untested on real radio (don't have one yet)
- Like any new radio, includes some changes to define handlings
- I'm doing to PR now despite brief simu only testing because the amount of rebase current activities generate !
- Probably superseedes https://github.com/opentx/opentx/pull/6221 based on 2.2

### CODE REVIEW

**Comment by jvckhevth** [comment]
Hey 3djc, 
I recently got a jumper t12 and crossfire micro running 2.2.3 everything flashed to latest firmware. I am able to run everything perfectly except one thing
When I click my [crossfire] lua script and execute it, I get stuck on the next page where it tells me XF micro tx and XF micro rx if quad is plugged in. But I cant scroll down or even click on the one it's one to get it to execute. Sometimes if I execute the device.lua it pops up the info screen but can't scroll down either. Any help is appreciated and it seems like I'm just running into a small bug since everything works flawlessly up until l get stuck on the executed page from crossfire.lua

**Comment by 3djc** [comment]
If you are running 2.2.3, then you are running JumperTX fork. We have introduced support for T12 in 2.3, that you can currently get as nightlies. I do not currenly have CRF equipement to test, but if you move to 2.3 and still have an issue, please open an issue for it and we will look into it

**Comment by jvckhevth** [comment]
Awesome you're the man. Will keep you posted its def the fork of jumper tx which I wasnt happy about I want it to say open tx when the sounds say welcome to open tx

**Comment by jvckhevth** [comment]
So I just went up to 2.3. The menu is more intuitive but still same problem. I can get right too the crossfire.lua and execute but then when I'm on the next page XF micro tx I still can select or scroll

**Comment by jvckhevth** [comment]
I will create an issue tomorrow when i can take some pictures of the radio. Thanks for the quick response!

**Comment by 3djc** [comment]
There is no need for pictures, we will have a look at provided CRSF scripts to make those compliant with the new 2.3 events

**Comment by kilrah** [comment]
Did you also take the SD card contents from OpenTX 2.3?

**Comment by jvckhevth** [comment]
Yeah I put the 2.3 card contents on too

**Comment by 3djc** [comment]
Yeah,  just add a lock, they need to be updated, will be done today

**Comment by jvckhevth** [comment]
Just cant click on XF micro tx or XF nano rx in the screen after I execute crossfire.lua, everything else is working for betaflight and all around the menu

**Comment by jvckhevth** [comment]
Awesome you guys rock.

**Comment by 3djc** [comment]
Could you try replacing the two CRSF script files on your by those ?

[test-crsf.zip](https://github.com/opentx/opentx/files/3371457/test-crsf.zip)

**Comment by jvckhevth** [comment]
works perfectly now thanks so much buddy!!!!!

**Comment by jvckhevth** [comment]
No betaflight lua script though now, unless I am hitting the wrong button to get into it from my main menu on the radio. On the x7 sd contents I was able to fully function betaflight when i held the down button now theres no betaflight with the t12 card contents. Last thing I promise but thank you so much for helping me with the crsf

**Comment by 3djc** [comment]
Yes BF scripts will need to be adapted for 2.3, they are aware of that, but you can do it yourself, not hard really

**Comment by jvckhevth** [comment]
Is there an easy way to explain? Or a link you could point me too. If not no worries and thanks for you're help

**Comment by 3djc** [comment]
oh wait, are you having issue with BF script button handling ? Or is it lauching it the issue (maybe not on SD, or something like that ?)

**Comment by jvckhevth** [comment]
Yeah it's not on the sd. Just curious to which lua I would add to it to make it back on thereSent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: 3djc <notifications@github.com> Date: 7/9/19  11:24 AM  (GMT-05:00) To: opentx/opentx <opentx@noreply.github.com> Cc: jvckhevth <Jack.heath.413@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [opentx/opentx] Add Jumper t12 support (#6451) oh wait, are you having issue with BF script button handling ? Or is it lauching it the issue (maybe not on SD, or something like that ?)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opentx/opentx/pull/6451?email_source=notifications\u0026email_token=AMR7POLNBCGBRNL2DON2A2DP6SUS3A5CNFSM4HPVAL2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZQTXYI#issuecomment-509688801",
"url": "https://github.com/opentx/opentx/pull/6451?email_source=notifications\u0026email_token=AMR7POLNBCGBRNL2DON2A2DP6SUS3A5CNFSM4HPVAL2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZQTXYI#issuecomment-509688801",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jvckhevth** [comment]
Nope just havent put them back on my card, curious as to which ones I need to put on to make it work on jumper with 2.3

**Comment by jvckhevth** [comment]
If you have a link to the bf lua like you did for the crossfire you did I think it's all I need

**Comment by 3djc** [comment]
Try the basic BF ones for a start, they are on their site, never have been part of our packs

**Comment by jvckhevth** [comment]
Will try when i get home, unbelievable support thank you

**Comment by jvckhevth** [comment]
So I tried the bf lua script 1.3.0 and it says script syntax error 
/BF/radios.lua:47
Radio not supported: t12

**Comment by 3djc** [comment]
It should be in next version, but is available on their git : https://github.com/betaflight/betaflight-tx-lua-scripts/blob/master/src/SCRIPTS/BF/radios.lua

**Comment by jvckhevth** [comment]
Do I have to turn that into my own lua? Or do I copy and paste that somewhere. sorry I'm new to all this

**Comment by jvckhevth** [comment]
I'm about to just run it without the bf lua. Can always just plug into laptop lol

**Comment by 3djc** [comment]
It is just a script (ie text) file, so you save it, copy and paste content, many ways to do it. I have donwloaded the full BF pack so you can try

[BF-test.zip](https://github.com/opentx/opentx/files/3374780/BF-test.zip)

**Comment by jvckhevth** [comment]
Works perfectly once again! Thanks so much man

**Pull request merged**
