### PR TITLE
should solve #2267

### PR DESCRIPTION
**Pull request by griebd**
Please have a look at the results, the screen is getting quite cluttered I think.

### CODE REVIEW

**Comment by bsongis** [comment]
Anyone?
I am not used to log viewer, it will be long for me to review!
If nothing I will quickly review it and accept!

**Comment by bsongis** [comment]
@romoloman I think you will better than me for this one :)

**Comment by projectkk2glider** [comment]
I have just tested this. I like this solution better then the current one. You got my vote for merge :+1:

**Comment by bsongis** [comment]
Thanks for your comment, I press the button :)

**Pull request merged**
