### PR TITLE
Fix for macOS 13 (Ventura) that changed sdcard filesystem type

### PR DESCRIPTION
**Pull request by christophe-calmejane**
Fix for #8983
PS: Fix imported from https://github.com/EdgeTX/edgetx/pull/2564

### CODE REVIEW

**Comment by dingrgh** [comment]
> Fix for #8983
> PS: Fix imported from [EdgeTX/edgetx#2564](https://github.com/EdgeTX/edgetx/pull/2564)

How can I get a 2.7.1+ Companion build that incorporates this fix? Right now, I don't have a working Companion that can import and edit my models  until 2.8 is released.

**Comment by christophe-calmejane** [comment]
I guess you have to wait for a nightly build, once the branch as been merged, or you can compile Companion yourself, or you can drop me an email and I'll share the build I made to test the fix

**Comment by carpentar** [comment]
christophe-calm , I somewhow got to this page.  I'm trying to update firmware on my Taranis X9D plus because I bought a plane for my son and I'm on this macbook trying to get things downloaded.  I'm a super novice at this computer thing.  When i'm in Opentx trying to download new firmware to my TX it asks me what I want to save it as. As it's never been downlaoded.   I just write opentx on desktop and says failed.  read-only.  How do i install the fix you mentioned here ? 

why is it this hard? please help

**Comment by shimsquat** [comment]
> ..or you can drop me an email and I'll share the build I made to test the fix

Hi christophe-calm, I'm also affected and desperate to get a 2.3.15 build for MacOS with this fix. May I kindly ask if this offer would also be valid for me :) If yes, how can I contact you, via l-acoustics email?

**Comment by christophe-calmejane** [comment]
> > ..or you can drop me an email and I'll share the build I made to test the fix
> 
> 
> 
> Hi christophe-calm, I'm also affected and desperate to get a 2.3.15 build for MacOS with this fix. May I kindly ask if this offer would also be valid for me :) If yes, how can I contact you, via l-acoustics email?

Oh course please do. I'll notarize the binary so you don't get warnings when running it. Hopefully this PR will be merged soon.

**Comment by shimsquat** [comment]
Thanks for the build, christophe-calmejane. I can confirm the fix works!

**Comment by lightbulbjim** [comment]
I would love to see this fixed.

**Comment by shimsquat** [comment]
Here‘s a workaround for the meantime - it‘s a shell script that unmounts both TX drives and remounts them correctly: [Link](https://www.rcgroups.com/forums/showpost.php?p=50209347&postcount=9232) 

Just scroll down to the end of the post.  Thanks to the contributor Jim.

**Comment by 3djc** [comment]
Thanks

**Comment by 3djc** [comment]
You can download a 2.3.15 release that is compatible with Ventura here : https://github.com/opentx/opentx/suites/9962691032/artifacts/482879168

We will also update the main download sever

**Comment by 3djc** [comment]
Main server updated, https://downloads.open-tx.org/2.3/release/companion/macosx/opentx-companion-2.3.15.dmg will get you a Ventura compatible one

**Comment by lightbulbjim** [comment]
Nice work, thanks!

**Comment by shimsquat** [comment]
👍

**Comment by flyingmutley** [comment]
good work many thanks

**Pull request merged**
