### PR TITLE
German spoken language fixed (C+ code)

### PR DESCRIPTION
**Pull request by rcbebo82**
tts_de.py also needs an update but i dont know how i can add this file to this pull request?
[tts_de.txt](https://github.com/opentx/opentx/files/535967/tts_de.txt)

Spoken numbers fixed:
100 -> "ein", "hundert"
1000 -> "ein", "tausend"
999 -> "9", "hundert", "99"

Timers:
60 seconds -> "eine", "minute"
3600 seconds -> "eine", "stunde"
120 seconds -> "2", "minuten"

### CODE REVIEW

**Comment by kilrah** [comment]
Looks good, just need a few coding style fixes particularly with the if/else (that were originally wrong in this file, refer to others)

**Comment by rcbebo82** [comment]
Fixed else syntax like described in the development wiki.

**Comment by 3djc** [comment]
Your indentation is wrong somewhere (see line 227 and 228)

**Comment by 3djc** [comment]
I have done some testing with those, and there are issues, I found at least:
playing 0m : meter
playing 100m : hundred coma meter
playing 101m : hundred coma einz meter

You seem for exemple in your code to decide that coma is now 104.wav, yet https://github.com/opentx/opentx/blob/master/radio/util/tts_de.py it is 102, it's not going to work like that

**Comment by kilrah** [comment]
That's becasue the file numbering has changed to make room for more, normal.

@rcbebo82 you should push the updated tts.py that matches the new requirements in that same branch

**Comment by rcbebo82** [comment]
I have also edit tts_de.py but i dont know how to add this file to this pull request im currently getting in SmartGit. Just take a look at the attached file in the first post.

**Comment by kilrah** [comment]
When you have your branch checked out just put the new tts.py in the repo, it will show as modified, include it in next commit and sync.

**Comment by rcbebo82** [comment]
Sorry @kilrah and @3djc for the work. I really need to understand how this github workflow works. Therefor im gettin currently in SmartGit. Bevor i tried it with git commanline tools but this seems much more complicated.

**Pull request closed without merging**
